### ISSUE TITLE
compiler script generation fails on OpenMPI

### ISSUE THREAD

**Issue by shanedsnyder** [darshan-hpc/darshan#122]
In GitLab by @shanedsnyder on Sep 24, 2015, 16:26

The darshan-gen-cc.pl script fails on generating a compiler wrapper due to the '-v' option not outputting anything to standard out. I don't think we even need this test specifically. I believe if we remove it and restructure a little, OpenMPI wrapper script generation will work.

my $version_out = `$input_file -v 2>/dev/null |head -n 1`;
if (!($version_out))
{
    printf STDERR "Error: failed to invoke $input_file with -v\n";
    exit(1);
}

**Comment by carns** [comment]
Deprecated; Darshan documentation covers how to deploy with OpenMPI without using wrapper generators.
