### ISSUE TITLE
darshan-util fails to build on Mac OS

### ISSUE THREAD

**Issue by shanedsnyder** [darshan-hpc/darshan#125]
In GitLab by @shanedsnyder on Sep 24, 2015, 16:26

Reported by Karen Schuchardt:

```text
gcc -I . -I . -I ./../ -DDARSHAN_CONFIG_H=\"darshan-util-config.h\" -g -O2
 -I/usr/include  darshan-parser.c darshan-logutils.o -o darshan-parser -lz
-lbz2
Undefined symbols:
  "_strndup", referenced from:
      _darshan_log_getjob in darshan-logutils.o
ld: symbol(s) not found
collect2: ld returned 1 exit status
make: *** [darshan-parser] Error 1
```

**Comment by shanedsnyder** [comment]
In GitLab by @shanedsnyder on Sep 24, 2015, 16:26

I tested this on Lion (10.7.3) using Xcode (4.3.2) and there was no issue in the compile and/or linking stage. I configured with no arguments.

gcc -I . -I ../../trunk/darshan-util -I ../../trunk/darshan-util/../ -DDARSHAN_CONFIG_H=\"darshan-util-config.h\" -g -O2  -I/usr/include  ../../trunk/darshan-util/darshan-parser.c darshan-logutils.o -o darshan-parser -lz -lbz2 
gcc -I . -I ../../trunk/darshan-util -I ../../trunk/darshan-util/../ -DDARSHAN_CONFIG_H=\"darshan-util-config.h\" -g -O2  -I/usr/include  -c ../../trunk/darshan-util/lookup3.c -o lookup3.o
gcc -I . -I ../../trunk/darshan-util -I ../../trunk/darshan-util/../ -DDARSHAN_CONFIG_H=\"darshan-util-config.h\" -g -O2  -I/usr/include  ../../trunk/darshan-util/darshan-convert.c darshan-logutils.o lookup3.o -o darshan-convert -lz -lbz2
gcc -I . -I ../../trunk/darshan-util -I ../../trunk/darshan-util/../ -DDARSHAN_CONFIG_H=\"darshan-util-config.h\" -g -O2  -I/usr/include  -c  ../../trunk/darshan-util/darshan-diff.c -o darshan-diff.o
gcc -I . -I ../../trunk/darshan-util -I ../../trunk/darshan-util/../ -DDARSHAN_CONFIG_H=\"darshan-util-config.h\" -g -O2  -I/usr/include  darshan-diff.o darshan-logutils.o -o darshan-diff -lz -lbz2
gcc -I . -I ../../trunk/darshan-util -I ../../trunk/darshan-util/../ -DDARSHAN_CONFIG_H=\"darshan-util-config.h\" -g -O2  -I/usr/include  ../../trunk/darshan-util/darshan-analyzer.c darshan-logutils.o -o darshan-analyzer -lz -lbz2
gcc -I . -I ../../trunk/darshan-util -I ../../trunk/darshan-util/../ -DDARSHAN_CONFIG_H=\"darshan-util-config.h\" -g -O2  -I/usr/include  ../../trunk/darshan-util/darshan-log-params.c -o darshan-log-params -lz -lbz2



eljobs:darshan-utils harms$ ../../trunk/darshan-util/configure 
checking for a BSD-compatible install... /usr/bin/install -c
checking for gcc... gcc
checking whether the C compiler works... yes
checking for C compiler default output file name... a.out
checking for suffix of executables... 
checking whether we are cross compiling... no
checking for suffix of object files... o
checking whether we are using the GNU C compiler... yes
checking whether gcc accepts -g... yes
checking for gcc option to accept ISO C89... none needed
checking how to run the C preprocessor... gcc -E
checking for grep that handles long lines and -e... /usr/bin/grep
checking for egrep... /usr/bin/grep -E
checking for ANSI C header files... yes
checking for sys/types.h... yes
checking for sys/stat.h... yes
checking for stdlib.h... yes
checking for string.h... yes
checking for memory.h... yes
checking for strings.h... yes
checking for inttypes.h... yes
checking for stdint.h... yes
checking for unistd.h... yes
checking if zlib is wanted... checking if bzlib is wanted... yes
checking for BZ2_bzCompressInit in -lbz2... yes
checking bzlib.h usability... yes
checking bzlib.h presence... yes
checking for bzlib.h... yes
checking for BZ2_bzCompressInit in -lbz2... (cached) yes
checking bzlib in /usr... ok
checking for pdflatex... no
checking whether byte ordering is bigendian... no
checking for off64_t... no
configure: creating ./config.status
config.status: creating Makefile
config.status: creating darshan-job-summary/bin/darshan-job-summary.pl
config.status: creating darshan-util-config.h
configure: WARNING: Please install pdflatex if you wish to use the darshan-job-summary.pl utility

**Comment by shanedsnyder** [comment]
In GitLab by @shanedsnyder on Sep 24, 2015, 16:26

strndup works on Mac OS 10.7 and later but not on earlier versions.

**Comment by carns** [comment]
Deprecated; Mac OS versions that exhibited this problem aren't prevalent now.
