### ISSUE TITLE
consider a new output mode for darshan-parser that is more machine parseable

### ISSUE THREAD

**Issue by shanedsnyder** [darshan-hpc/darshan#271]
In GitLab by @carns on Apr 26, 2020, 07:21

We probably should not change the existing --perf output in case existing analysis tools depend on it, but it would be helpful to have a variation that:

* includes the module name in each line of output (to make it easier to grep)
* only shows what's accepted as the best performance estimate ("by_slowest")
* also outputs bytes
* also outputs time (rate, bytes, and time should all be directly related)

This output mode would probably be preferred for future ML analysis tools.

**Comment by carns** [comment]
Deprecated; moving forward we will be discouraging darshan-parser for this use case in favor of the pydarshan bindings.
