### ISSUE TITLE
Remove automatically generated files from the repo

### ISSUE THREAD

**Issue by shanedsnyder** [darshan-hpc/darshan#297]
In GitLab by @wkliao on Feb 9, 2021, 02:36

May I suggest to remove the following 2 files from the gitlab repo?
```
    darshan-runtime/configure
    darshan-runtime/darshan-runtime-config.h.in
```
The former is generated by autoconfig and the latter autoheader.

**Comment by shanedsnyder** [comment]
In GitLab by @carns on Feb 9, 2021, 13:31

Yep, I agree completely.  Same probably for the darshan-util side as well.

We'll also need to check our release checklist and make sure they get generated for release tarballs.

**Comment by shanedsnyder** [comment]
In GitLab by @shanedsnyder on Feb 9, 2021, 13:53

I'll take a stab at this -- we've put this off long enough! :grin:

**Comment by shanedsnyder** [comment]
In GitLab by @wkliao on Feb 14, 2021, 02:59

They have been removed in !77

**Comment by carns** [comment]
Closing issue; this was completed in autotools merge to origin/main.
