### ISSUE TITLE
convert build system to automake and libtool

### ISSUE THREAD

**Issue by shanedsnyder** [darshan-hpc/darshan#301]
In GitLab by @carns on Feb 24, 2021, 12:58

@wkliao is working on this already in !77 .  This issue is tracking it for inclusion in an upcoming release milestone.

We should complete #300 before automake transition, though.

**Comment by shanedsnyder** [comment]
In GitLab by @carns on Mar 3, 2021, 16:06

The following fork/branch has a prototype spack package modification that will build both old versions and the new automake version:

https://github.com/carns/spack/tree/carns/darshan-automake

This isn't ready for submission upstream; it points to @wkliao 's darshan branch for @develop installs right now.  There is also a problem with one of the configure arguments to fix.

Still need to compare packages installed with this setup:

* [x] does 3.2.1 installed with this package match 3.2.1 installed with the stock upstream spackage?  It might not be installing the same library variations; need to check.  May have caused some differences by running autoreconf in build that was previously always using pre-generated configure script.
* [x] does @develop match the files installed by 3.2.1?

**Comment by shanedsnyder** [comment]
In GitLab by @carns on Mar 4, 2021, 12:52

Configuration works in spack now with existing options.  Will work on comparing the above installations now.

**Comment by shanedsnyder** [comment]
In GitLab by @carns on Mar 4, 2021, 13:18

darshan-runtime 3.2.1 built with the new spackage is missing the following, will investigate:

```
< ./lib/libdarshan.a
15d13
< ./share/ld-opts/darshan-mpiio-ld-opts
17d14
< ./share/ld-opts/darshan-pnetcdf-ld-opts
```

Probably indicates that the new spackage isn't building darshan-runtime with mpi support, will debug.

**Comment by shanedsnyder** [comment]
In GitLab by @carns on Mar 4, 2021, 15:12

The above issue is fixed in the spack fork/branch.

**Comment by shanedsnyder** [comment]
In GitLab by @carns on Mar 8, 2021, 15:15

All tests pass.  Also used a spack-installed darshan-runtime@develop package on Cori to generate a log and confirm it's contents.  Can merge when ready.

**Comment by shanedsnyder** [comment]
In GitLab by @wkliao on Mar 8, 2021, 17:02

That is great! I will rebase my PnetCDF branch to create a merge request, once !77 is merged.

**Comment by carns** [comment]
Closing issue; this was merged to origin/main some time ago.
