### ISSUE TITLE
analysis utility to generate heat maps from Darshan DXT data

### ISSUE THREAD

**Issue by shanedsnyder** [darshan-hpc/darshan#307]
In GitLab by @carns on Mar 8, 2021, 14:05

The heat map would show, per process, how I/O intensity is distributed across time and ranks.  Would be helpful for getting an initial intuitive feel for hot spots and burstiness.  Could also be used to calculate throughput over time intervals, and could be annotated with metadata access intensity and file names.

Ideally this would be a Python tool that utilizes the Darshan Python bindings to produce a 2D array (ranks * nbins), where nbins is fixed regardless of the runtime, and access that span time bins are proportionally divided across them.

If we could come up with a reasonably clear/concise graph it could be one of the lead figures in a revised darshan-job-summary.

**Comment by carns** [comment]
Closing this issue; this has been covered by work in the the pydarshan-devel branch and the pydarshan-job-summary-v1 milestone.
