### ISSUE TITLE
BLD: re-configure `--with-log-path=` doesn't rebuild

### ISSUE THREAD

**Issue by shanedsnyder** [darshan-hpc/darshan#313]
In GitLab by @tylerjereddy on Mar 26, 2021, 10:51

The following cycle doesn't actually re-trigger a build of the shared object(s) when only changing the path specified by `--with-log-path=` at the configure stage.

- `./configure --prefix=/yellow/usr/projects/eap/users/treddy/darshan_install --with-log-path=/yellow/usr/projects/eap/users/treddy/darshan_logs --with-jobid-env=PBS_JOBID CC=mpicc`
- `make`
- `make install`

To make matters slightly worse for newcomers like myself, `darshan-config --log-path` will correctly reflect the re-configured log path, but that path never gets embedded into the runtime shared object library and `darshan-config` has no true connection to the string/path embedded in the binary.

(also confirmed by @shanedsnyder)

In the interim, I can use `make clean` of course.

**Comment by shanedsnyder** [comment]
In GitLab by @tylerjereddy on Mar 26, 2021, 10:53

changed the description

**Comment by shanedsnyder** [comment]
In GitLab by @tylerjereddy on Mar 26, 2021, 10:53

changed the description

**Comment by shanedsnyder** [comment]
In GitLab by @carns on Mar 30, 2021, 14:54

I just tested this using @wkliao's automake branch !77 and confirmed that it is fixed there.  We are waiting to get that merged after settling down some of the other pending MRs, though.

Leaving this issue open for now and categorizing in the 3.3.0 milestone; assuming we get the autotools migration done for that release then it will pick up this fix.

**Comment by carns** [comment]
This is fixed in origin/main with the autotools build system.
