### ISSUE TITLE
MAINT: matplotlib module should be renamed

### ISSUE THREAD

**Issue by tylerjereddy** [darshan-hpc/darshan#384]
It is not good to have a module named `matplotlib.py` in our library--it can interfere with the import of the popular third-party plotting library of the same name when developing code.

For example, I'm having to do this locally for some work:

`darshan/experimental/plots/matplotlib.py -> darshan/experimental/plots/matplotlib_mod.py`

when writing modules in that path that leverage `matplotlib` (the external package).

**Comment by nawtrey** [comment]
Looks like this was fixed via gh-404. Closing.
