### ISSUE TITLE
CI: Setup CI for PyDarshan 

### ISSUE THREAD

**Issue by nawtrey** [darshan-hpc/darshan#407]
As Tyler mentioned in https://github.com/darshan-hpc/darshan/issues/406#issuecomment-869023588, we should setup CI for `pydarshan`. 

A summary of Tyler's and Phil's comments: 
- Setup CI on only on the `pydarshan-devel` branch, for now
   * build darshan-util, then pydarshan, then running the `pytest` suite for a few versions of Python (3.7-3.9)
   * Run `mypy` (or whatever type checker you like to use)
- Want to be able to run this sort of test equally well from both GitHub and the command line

[Travis CI](https://travis-ci.org/) is a popular option, and I've set it up before on another GitHub project, but I'm planning on moving to [GitHub Actions](https://github.com/features/actions) because of the new plan schedule Travis has (see [here](https://blog.travis-ci.com/2020-11-02-travis-ci-new-billing)). If I understand it correctly, they give you 1,000 free run time minutes but after that you have to purchase a plan. 

If anyone has any recommendations other than GitHub Actions feel free, I'm not an expert on CI so I'm not married to any particular one.

**Comment by nawtrey** [comment]
GitHub does have a list of popular options [here](https://github.blog/2017-11-07-github-welcomes-all-ci-tools/), with Travis being the most popular.

**Comment by tylerjereddy** [comment]
Travis is tied to a finite set of credits these days, so I wouldn't use that. GitHub actions or Azure pipelines seems fine. We need a fair bit of work before we're ready to run `mypy` I think, so that would probably be added to CI later.

**Comment by tylerjereddy** [comment]
Most of the debug work for setting it up could be done on a fork as well, to avoid permissions issues/noise until ready. I think GitHub actions and Azure pipelines both have pretty solid docs, plus tons of open source projects have well thought out CI setups with those services that can be used as inspiration.

**Comment by carns** [comment]
+1 vote for github actions (just for simplicity/familiarity).

**Comment by tylerjereddy** [comment]
Fixed by #414; CI is now running in i.e., #397 fort `pydarshan-devel` targeted PRs. So, I'll close this.

Carefully considered expansions to the CI may still be helpful for things like checking the type hints with bleeding edge versions of NumPy/mypy/various stubs, but those can be separate issues/PRs.

**Comment by tylerjereddy** [comment]
Oh yeah, we have to manually close issues that are fixed on `pydarshan-devel` because MRs not targeted at `main` are not formally considered "merged" by GitHub. I can see why they do that, but for our purposes probably best to close issues when dealt with on that branch.
