### ISSUE TITLE
Documentation for building darshan-runtime might be outdated

### ISSUE THREAD

**Issue by HenryYihengXu** [darshan-hpc/darshan#417]
I'm trying to build the most recent stable version darshan-3.3.1, and I'm following the instruction on [https://www.mcs.anl.gov/research/projects/darshan/docs/darshan-runtime.html](https://www.mcs.anl.gov/research/projects/darshan/docs/darshan-runtime.html) (the `darshan-runtime.txt` has the same instruction).

However, this version doesn't contain a `configure` file. I tried running `autoconf` in `darshan-runtime` directory. It did generate a `configure` file, but it gave me the following errors: 

```
configure.ac:19: error: possibly undefined macro: AC_CONFIG_MACRO_DIRS
      If this token and others are legitimate, please use m4_pattern_allow.
      See the Autoconf documentation.
configure.ac:21: error: possibly undefined macro: AM_INIT_AUTOMAKE
configure.ac:22: error: possibly undefined macro: AM_SILENT_RULES
configure.ac:23: error: possibly undefined macro: AM_MAINTAINER_MODE
configure.ac:649: error: possibly undefined macro: AM_CONDITIONAL
```

Also, I cannot run the generated `configure` file. It gave me:

```
configure: error: cannot find install-sh, install.sh, or shtool in ../maint/scripts "."/../maint/scripts
```

Could you help me on this issue and maybe update your docs? Thank you!

**Comment by carns** [comment]
Hi @HenryYihengXu , thanks for the bug report.

Where exactly did you get the 3.3.1 release from?  The configure file is present in ftp://ftp.mcs.anl.gov/pub/darshan/releases/darshan-3.3.1.tar.gz, I think.

If you use origin/main out of git it will not be there, though.  We recently converted fully to autotools and (along with that change) took the generated configure script out of revision control, but there hasn't been a release with that change yet so I want to double check what version you are using.

**Comment by HenryYihengXu** [comment]
Hi @carns. Looks like I'm on the main branch. Somehow when I switched to the darshan-3.3.1 tag I didn't do it correctly with git. But thanks for your reply!

**Comment by carns** [comment]
Ok- great!  Glad we got it sorted out.

For reference if you want to work with the main branch at some point in the future, just run the `./prepare.sh`  script at the top level to generate the configuration files.  There have been some changes to configure arguments that are documented in the in-tree documentation, but otherwise it should seem very similar.
