### ISSUE TITLE
TST: test infrastructure for pulling in log test data

### ISSUE THREAD

**Issue by tylerjereddy** [darshan-hpc/darshan#420]
Described by Phil here: https://github.com/darshan-hpc/darshan/pull/396#issuecomment-865955610

Some points to address might be:

- good examples of open source (Python) projects that pull in external test data and skip/xfail gracefully in the absence of a network connection?
- should there be an "offline fallback" or command line argument that can be provided to pull the data in from a local clone of the test data repo?

Normally, network-dependent testing infrastructure is best avoided in favor of i.e., small representative test cases for specific functions where possible (i.e., maybe avoid adding a log file if you can just add a small array-based test for a function in the control flow).

**Comment by carns** [comment]
It seems reasonable to me to have a combination of some basic tests that can be done purely with local files, and more extensive tests that require downloading something.  I don't known whether it makes more sense for that choice to be automatic or implied based on whether the download is successful or not.

**Comment by tylerjereddy** [comment]
Let me try to prototype this with a feature branch of the logs repo today.

**Comment by tylerjereddy** [comment]
I've opened a PR with a working prototype/example test using all the log files in the current logs repo, and it gracefully handles the case when the logs are absent: https://github.com/darshan-hpc/darshan-logs/pull/2

**Comment by shanedsnyder** [comment]
Can this issue be closed? I think this is all working.

**Comment by tylerjereddy** [comment]
Yeah, this works pretty well now I think. There may be one future step where we have a genuine package on PyPI for the logs repo and/or one of third-party libraries for delivering data assets discussed in https://github.com/darshan-hpc/darshan-logs/issues/15, but that seems like something we won't do anytime soon.
