### ISSUE TITLE
CI: add codecov

### ISSUE THREAD

**Issue by tylerjereddy** [darshan-hpc/darshan#421]
Adding [codecov](https://about.codecov.io/) to the pydarshan CI may make sense to see the test line coverage on diffs.

It can be flaky, probably best to mimic the settings from other large OSS projects. i.e.,:

- disable the annoying bot comments that show up in PRs
- probably disable codecov ever actually failing the CI, because there are so many cases where it isn't practical to get the coverage threshold
- mostly just a convenient way for reviewers to click through to a coverage report for a PR if the `%` coverage on the diff looks a bit low, to see what is going on

**Comment by tylerjereddy** [comment]
After merging #434, the only remaining steps for this to be closed should be:

- @nawtrey can help @shanedsnyder setup the codecov app for this repo if any help is needed there (since Nik just did the same thing on their fork)
- make sure an example PR looks ok when targeted at `pydarshan-devel`

**Comment by tylerjereddy** [comment]
@shanedsnyder has Nik touched based with you about this? I think the process is basically just to turn on the codecov "app" for the repo.

The main concern I might have is that we only have the config file on `pydarshan-devel`, so there's perhaps a non-zero chance of getting undesired noise on `main`, but hopefully that doesn't happen or could be easily silenced with a config file on `main` if that starts to happen.

**Comment by shanedsnyder** [comment]
I'll have a look and see if I can figure out how to turn it on. Hopefully we can make it not grumpy about lack of coverage outside of pydarshan directory, as well.

**Comment by shanedsnyder** [comment]
I _think_ this is done (I enabled codecov for darshan-hpc at least)? Not exactly sure how to check, looks like you might just need to confirm it works after setting up an action for running this on commits or something?

**Comment by tylerjereddy** [comment]
@shanedsnyder @nawtrey I don't see the reports in the CI matrix yet (I merged gh-467 and rebased gh-397 with no success on getting the reports).

Maybe Nik can confirm that what you did matches what they did on their fork. Sometimes @thomasrockhu on the codecov team is kind enough to take a quick look as well.

The pull requests are registering on the codecov site here: https://app.codecov.io/gh/darshan-hpc/darshan/pulls?page=1&state=open&order=-pullid

Just not seeing the CI matrix entries yet.

**Comment by nawtrey** [comment]
I never messed with any of the GitHub apps to get `codecov` working on my fork. When I opened my test PR's the `codecov` checks automatically popped up, so I never had to go looking for how to turn things on.

**Comment by thomasrockhu** [comment]
Hey all, I don't think I quite understand the issue here. What's not happening right now?

**Comment by thomasrockhu** [comment]
Looping back, looks like this was an issue with posting GitHub statuses from a fork. Solved by adding the Codecov app integration.

**Comment by tylerjereddy** [comment]
Yeah, I think most OSS projects just add the APP these days, thanks all.

I'll close this since it is clearly working properly in #397 with CI matrix image captured below:

![image](https://user-images.githubusercontent.com/7903078/131714563-03dff02d-ca3a-45b7-a91f-88cbfdf2c8c8.png)
