### ISSUE TITLE
Python job summary - plotly draft 

### ISSUE THREAD

**Issue by nawtrey** [darshan-hpc/darshan#431]
As mentioned [here](https://github.com/darshan-hpc/darshan/pull/396#issuecomment-867691760), [plotly](https://plotly.com/python/) is a potential solution for generating a report in PDF and HTML formats. After digging into it a bit, it looks like there are a few ways we could use `plotly` to generate a report. 

I'll go through the methods I've come up with first, then my notes on each.

Methods
---------
1. Convert our `matplotlib`/`seaborn` figures into `plotly` figure objects  
2. Reconstitute our figures in `plotly` using the `pandas` dataframes output by the various plotting functions
3. Save static images of our figures and read them into `plotly` 

Each of the above methods would then make a static HTML report and convert the html to a PDF using something like [`xhtml2pdf`](https://xhtml2pdf.readthedocs.io/en/latest/).

Notes
------
1. As far as I know, the only way to convert `matplotlib`/`seaborn` figures to `plotly` figures is to use their function `plotly.tools.mpl_to_plotly()`, and this was deprecated already (see [here](https://github.com/plotly/plotly.py/issues/1568)). So this one seems like a non-starter. 
2. This one is likely the most work considering we would have to write new code to generate the figures. I think this one is also a non-starter due to that alone, although `pandas` does have a `plotly` backend (see [here](https://plotly.com/python/pandas-backend/)). 
3. This is probably the easiest and most tractable. It's a little quirky since we have to save the figures we generate, and the `plotly` figures are basically empty plots with a background set to the image that we import, but I *was* able to create an html report this way, even though it was super basic (just 3 figures pasted in). The current things to tackle would be generating an html template that can contain all the things we want, and then finding a way to convert that to a pdf.  

In general, `plotly` seems very html and online-focused. They have added offline variants of a lot of their plotting functions, but they started from the perspective of uploading things to `plotly` and using their interactive UI, so it probably *can* do what we need but I don't think it was really designed for our use case. Additionally, figuring out how to generate the html correctly such that one of the html->pdf converters works has been difficult. `xhtml2pdf`'s [documentation](https://xhtml2pdf.readthedocs.io/en/latest/) is very limited, and the alternative they recommend [`weasyprint`](https://weasyprint.org/) seems a bit more cumbersome to install, so I'm not sure if that's a viable option.  

The script I wrote is pasted below. You should be able to drop it anywhere, just keep in mind it is going to save the files (`report.html`, `report.pdf`, and a .png for each figure) in your current working directory. It can be executed using the following command:

`python generate_report.py ~/path/to/darshan/log.darshan`
 
<details>
<summary> generate_report.py </summary>
<pre>

```python
import os
import sys
import glob
import argparse

import plotly
from xhtml2pdf import pisa
import plotly.graph_objects as go
import base64

import darshan
darshan.enable_experimental()
from darshan.experimental.plots.plot_opcounts import plot_opcounts
from darshan.experimental.plots.plot_dxt_heatmap import plot_heatmap
from darshan.experimental.plots.plot_access_histogram import plot_access_histogram


def get_plotly_figures(fig_paths):

    figure_list = []
    for path in fig_paths:
        encoded_image = base64.b64encode(open(path, "rb").read())
        img = "data:image/png;base64,{}".format(encoded_image.decode())
        layout = go.Layout(
            images=[
                go.layout.Image(
                    source=img,
                    x=0.5,
                    y=0.5,
                    sizex=1,
                    sizey=1,
                    xanchor="center",
                    yanchor="middle",
                )
            ],
            template="plotly_white",
        )
        fig = go.Figure(layout=layout)
        # try to cleanup the formatting some, still not right
        fig.update_xaxes({"visible": False})
        fig.update_yaxes({"visible": False})
        fig.update_layout(
            autosize=False,
            width=800,
            height=800,
            margin=dict(l=0, r=0, b=0, t=0, pad=0),
        )
        figure_list.append(fig)

    return figure_list


def figures_to_html(fig_list):

    # turn off all of the interactive things we don't want
    config = dict(staticPlot=True, displayModeBar=False, displaylogo=False)

    static_report = "<html><head></head><body>" + "\n"
    for fig in fig_list:
        # inner_html = fig.to_html().split('<body>')[1].split('</body>')[0]
        inner_html = plotly.io.to_html(
            fig=fig,
            config=config,
            auto_play=False,
            include_plotlyjs=True,
            full_html=False,
            default_width=500,
            default_height=400,
        )
        static_report += inner_html
    static_report += "</body></html>"
    return static_report


def save_html_to_file(source_html, output_filename):
    # open output file for writing
    result_file = open(output_filename, "w")
    # write html to file
    result_file.write(source_html)
    # close output file
    result_file.close()

def convert_html_to_pdf(source_html, output_filename):
    # open output file for writing (truncated binary)
    result_file = open(output_filename, "w+b")
    # convert HTML to PDF
    pisa.CreatePDF(
        src=source_html,
        dest=result_file,
        default_css=None,
        xhtml=False,
        encoding=None,
        xml_output=None,
        raise_exception=True,
    )
    # close output file
    result_file.close()


def main(filepath, save_html=True):
    # generate the darshan report
    report = darshan.DarshanReport(filepath, read_all=True)

    # generate figures to plot
    hmap_fig = plot_heatmap(
        log_path=filepath, mods=["DXT_POSIX"], ops=["read", "write"], xbins=200
    )
    opct_fig = plot_opcounts(report=report)
    hist_fig = plot_access_histogram(report=report, mod="POSIX")

    # get the savepaths for each figure
    cwd = os.getcwd()
    hmap_savepath = os.path.join(cwd, "hmap.png")
    opct_savepath = os.path.join(cwd, "opct.png")
    hist_savepath = os.path.join(cwd, "hist.png")

    # save each figure at their respective save paths
    hmap_fig.savefig(hmap_savepath, dpi=300)
    opct_fig.savefig(opct_savepath, dpi=300)
    hist_fig.savefig(hist_savepath, dpi=300)

    # collect the save path for each figure
    fig_paths = [hmap_savepath, opct_savepath, hist_savepath]
    # use the save paths to generate plotly figures
    plotly_figures = get_plotly_figures(fig_paths=fig_paths)
    # use the plotly figures to generate a static html report
    static_report = figures_to_html(fig_list=plotly_figures)

    # save the static report as an html file
    save_html_to_file(static_report, output_filename="report.html")
    # try to convert the html to a pdf
    convert_html_to_pdf(static_report, output_filename="report.pdf")


if __name__ == "__main__":
    # get the path to the file(s) to be read in
    parser = argparse.ArgumentParser()
    parser.add_argument(
        "datapath",
        nargs="?",
        help="Specify path to darshan log file or directory with darshan logs",
    )
    args = parser.parse_args()
    data_path = args.datapath

    if os.path.isfile(data_path):
        # individual file case
        files_to_process = [data_path]
    elif os.path.isdir(data_path):
        # directory case
        files_to_process = glob.glob(os.path.join(data_path, "*.darshan"))

    for filepath in files_to_process:
        main(filepath=filepath)
```

</pre>
</details>

**Comment by tylerjereddy** [comment]
> Each of the above methods would then make a static HTML report and convert the html to a PDF using something like xhtml2pdf.

That likely wouldn't give us any advantage over the html template we currently have--my main thought was using `plotly` as the direct source of saving in either PDF or html modes (which it can do).

Why does method 1 require using a converter for html->PDF instead of using `plotly` to directly save in the respective formats?

It doesn't look likely that this will be a productive path forward, and I'm assuming you've looked into other libraries out there as well, but I don't quite get why we would use the convert for approach number 1.

**Comment by nawtrey** [comment]
> Why does method 1 require using a converter for html->PDF instead of using `plotly` to directly save in the respective formats?

They recommend using `xhtml2pdf` [here](https://plotly.com/python/v3/pdf-reports/) for generating "pdf reports", but for individual figures you can save them as pdfs with ease. I think if wanted to use their figure -> pdf approach, we would have to create the entire figure in a single report, convert it to a `plotly` figure, then save it as a pdf.

**Comment by tylerjereddy** [comment]
Ok, that's good to know. We're basically doing approach `3` with #386 at the moment.

It sounds like html->PDF converters are a bit fragile, but if one could suit our needs well enough we could go that route to avoid separate "canvas" layout code for each format.

My only concern there is that PDF is the "main priority," but the current genshi approach is html-first and then we'd tag on a "hope for the best" html->PDF conversion at the end.

**Comment by tylerjereddy** [comment]
As discussed in the meeting today, we'll likely prioritize generating PDFs only for now.

May be worth an hour or two of checking to see if one of the Python PDF generators might suit our purpose (and if they are still maintained)--i.e., https://stackoverflow.com/a/51881060/2942522

**Comment by nawtrey** [comment]
Exploring other options, I took a stab at making a simple report using [`fpdf2`](https://pyfpdf.github.io/fpdf2/index.html), which I've attached. I generated it using the log `examples/example-logs/ior_hdf5_example.darshan` and some of the experimental plotting functions. Most of what's in there was just to test different features of `fpdf2`, but I did give it some of the metadata things from the original job summary. 

[report_ior_hdf5_example.pdf](https://github.com/darshan-hpc/darshan/files/6942067/report_ior_hdf5_example.pdf)

`fpdf2` Notes
--------------
1. There isn't a way to read in `matplotlib` objects, so we have to store the figures locally and import them into the PDF. This is similar to what I was doing with `plotly`, and so far I haven't heard any complaints about that aspect, so maybe that's not a big deal. The biggest issue I see is if we want to have figures adjacent to each other, or we want to the figure axes to align in some way, this is kind of annoying to do by adjusting coordinate values/image sizes in the PDF code. You can see the adjacent figures in the report are not really aligned, for example.  
2. `fpdf2` does have the ability to make tables, but I don't think it offers much in terms of styling (without writing html), and I'm not sure if it supports any sort of complex table structures. If we want to add tables we can use `matplotlib` which likely has more flexibility, save it to disc, then read them in (like all other figures). 
3. Adding text/annotations is probably not much easier than using `matplotlib` directly. The interface does allow you to left/center/right justify text in user-defined cells, place objects at the set margins, etc., so that's probably a win for `fpdf2`.

All in all I would say `fpdf2` is a workable solution for generating a PDF. I had an easier time making a somewhat useful PDF report with this than I did making a html report with `plotly`, despite `fpdf2` having incomplete documentation. Unless there are any objections I think it is worth a shot.

**Comment by tylerjereddy** [comment]
Not sure what others think, but looks reasonable to me.

A few thoughts:

- `pandas` can export tables to `html` format directly, and do some pretty slick formatting/coloring things with missing values and so on, so that might be an option if `fpdf2` can handle the html table format
- `fpdf2` is open source so with the right permissions we may be able to move shims that are useful to us directly upstream
- Python temporary directories could be used for the plot pass-through I suppose, to avoid leaving extra plot artifacts for users, etc.
- the dependencies don't look too terrible at first glance
- looks like they use `qpdf` for unit testing PDF output--that may also be useful for regression testing at some point

**Comment by shanedsnyder** [comment]
Making a quick pass over old issues, and closing this.

We ended up using `mako` to generate HTML reports, rather than generating PDFs, which has turned out to be a good decision, IMO.
