### ISSUE TITLE
BUG: filepath/hash mapping in Python bindings

### ISSUE THREAD

**Issue by tylerjereddy** [darshan-hpc/darshan#432]
Reported by @nawtrey in #397, the integer filepaths are bad below. Probably in the Python bindings because Shane checked the raw C side.

```python 
import darshan

path = "/Users/nawtrey/darshan-tools/data/noposixopens.darshan"
report = darshan.DarshanReport(path, read_all=True)
file_id_dict = report.data["name_records"]
for hash, fs in file_id_dict.items():
    print(hash, fs)
```

creates the following output:

```
$ python test.py 
14734109647742566553 3126844023
15920181672442173319 3710437467
7238257241479193519 3599639208
3386817440460129181 /global/project/3706887080
11731316394082063854 /global/project/3722469739
```

**Comment by tylerjereddy** [comment]
@carns @shanedsnyder 

Shane indicated that the C code was fine in https://github.com/darshan-hpc/darshan/pull/397#issuecomment-890010466, but I went right into the guts of the C code and I can reproduce the results right there on feature branch `pydarshan-devel`:

```diff
diff --git a/darshan-util/darshan-logutils.c b/darshan-util/darshan-logutils.c
index db7ae1a..2e5ed5b 100644
--- a/darshan-util/darshan-logutils.c
+++ b/darshan-util/darshan-logutils.c
@@ -2198,6 +2198,8 @@ void darshan_log_get_name_records(darshan_fd fd,
     int i = 0;
     HASH_ITER(hlink, name_hash, curr, tmp)
     {
+        printf("id from C: %llu\n", curr->name_record->id);
+        printf("name from C: %s\n", curr->name_record->name);
         (*name_records)[i].id = curr->name_record->id;
         (*name_records)[i].name = curr->name_record->name;
         i++;

```

```
id from C: 14734109647742566553
name from C: 3126844023
id from C: 15920181672442173319
name from C: 3710437467
id from C: 7238257241479193519
name from C: 3599639208
id from C: 7764981385333365083
name from C: /global/cscratch1/984505216
id from C: 4112700762859735818
name from C: /global/cscratch1/2460343576
<snip>
```

And if I do a clean rebuild on latest version of `main` (including the new autoreconf procedure, adjusting the Python versions so the tests can pass, etc.), I still see the problem (this list also looks shorter on `main`, though I focused mostly on the values at the top with integer "names"):

```
id from C: 14734109647742566553
name from C: 3126844023
id from C: 15920181672442173319
name from C: 3710437467
id from C: 7238257241479193519
name from C: 3599639208
id from C: 3386817440460129181
name from C: /global/project/3706887080
id from C: 11731316394082063854
name from C: /global/project/3722469739
```

**Comment by shanedsnyder** [comment]
It doesn't look like there's a bug here in the C code or Python bindings, actually.

These examples are simply printing out every single file record (and corresponding record ID, i.e., the hash value) that Darshan is aware of. In the example log we are considering, anonymization was used to mask identifying details about the log file, including record names. So, some of the records have names like "/global/project/3722469739", where Darshan has kept the mount point in tact (/global/projects), but anonymized the file name (yielding 3722469739). The other example record names that don't have a file mount point preceding them are actually just STDIO records for STDIN, STDOUT, STDERR, which obviously do not have associated mount points. So this all actually looks okay, just didn't realize we were anonymizing this log.

There's still a problem with the analysis that sparked this discussion though. I'll comment more there, but will close this as I don't think there's a bug in the C lib or Python bindings.
