### ISSUE TITLE
ENH: performance improvement(s) for cffi_backend.log_get_generic_record()`

### ISSUE THREAD

**Issue by nawtrey** [darshan-hpc/darshan#440]
Hand-in-hand with issue #439, it seems there are some performance bottlenecks that can be improved upon in `cffi_backend_log_get_generic_record()`. In the `if dtype == pandas` [block](https://github.com/darshan-hpc/darshan/blob/main/darshan-util/pydarshan/darshan/backend/cffi_backend.py#L358), dataframes are being flipped, then flipped back to append the id/rank data, for each record. This can probably be avoided entirely or done after all of the dataframes are concatenated. There are also some loops that can probably be cleaned up, or at least changed to generate an array beforehand then assign the data.

**Comment by tylerjereddy** [comment]
I'll close this because of gh-447, though I note that we should probably just read the records in completely in C/CFFI as #451 notes--no matter how fast we make that inner loop, without enough records we're still bound by interpreted Python loops, which will become painful for large enough data.
