### ISSUE TITLE
ENH: Add POSIX support to heatmap code (or support some other coarser data format)

### ISSUE THREAD

**Issue by nawtrey** [darshan-hpc/darshan#454]
The heatmap figure code currently only supports darshan logs with the `DXT_POSIX` module. Ideally it would be able to handle `POSIX` as well, since we want our reports to contain the heatmap as the first figure. 

I'll have to dig into this for #445 since its current work around is to simply plot nothing for non-DXT logs.

**Comment by tylerjereddy** [comment]
I'm pretty certain Phil said we don't have to do that when I asked him during one of the meetings. There may be, at some point in the future, a way for the C library to provide us with something a bit coarser than what we currently get with DXT data, but at the moment I think we agreed this doesn't make much sense and isn't a priority.

**Comment by nawtrey** [comment]
Feel free to close this then, I'll just add a comment about my heatmap-related concerns in #445.

**Comment by tylerjereddy** [comment]
can stay open as a reminder that this may happen at some point for huge runs where DXT is too expensive so darshan needs to provide some kind of summary collection of DXT-like data

**Comment by carns** [comment]
Closing this to track in #468 as a runtime instrumentation library task.
