### ISSUE TITLE
Missing file darshan-base-ld-opts.in

### ISSUE THREAD

**Issue by wkliao** [darshan-hpc/darshan#455]
Got an error during make.
```
Making all in ld-opts
make[6]: *** No rule to make target 'darshan-base-ld-opts', needed by 'darshan-ld-opts'.  Stop.
```
File 'darshan-runtime/share/ld-opts/darshan-base-ld-opts.in' is missing.

**Comment by wkliao** [comment]
FYI. Here is the make command I used.
```
make distcheck DISTCHECK_CONFIGURE_FLAGS="--with-log-path=$HOME/Darshan/LOG --with-jobid-env=NONE --without-mpi"
```

The two lines below duplicate file `darshan-base-ld-opts` to `darshan-ld-opts`.
https://github.com/darshan-hpc/darshan/blob/1c1a31cf44d5b2a6548a2fe95284dbbe88651bfc/darshan-runtime/share/ld-opts/Makefile.am#L40-L41

This is different from my automake_libtool PR, which used file `darshan-base-ld-opts.in` to generate file `darshan-base-ld-opts` with contents shown below. Which approach is desired?
If it is the one currently used in main branch, then maybe we can simply rename file `darshan-base-ld-opts` to `darshan-ld-opts`.
https://github.com/darshan-hpc/darshan/blob/4916aa3a2255b0c15bacf33a036b170e97bab603/darshan-runtime/share/ld-opts/Makefile.am#L30-L31
```
--undefined=MPI_Init
--undefined=__wrap_MPI_Init
--undefined=MPI_Wtime
--wrap=MPI_Init
--wrap=MPI_Init_thread
--wrap=MPI_Finalize
--wrap=PMPI_Init
--wrap=PMPI_Init_thread
--wrap=PMPI_Finalize
@DARSHAN_POSIX_LD_OPTS@
@DARSHAN_STDIO_LD_OPTS@
@DARSHAN_MPIIO_LD_OPTS@
@DARSHAN_PNETCDF_LD_OPTS@
@DARSHAN_HDF5_LD_OPTS@
@DARSHAN_MDHIM_LD_OPTS@
@DARSHAN_APMPI_LD_OPTS@
```

**Comment by carns** [comment]
I just tried to reproduce this and hit a problem also, but in my case it was a different problem:

```
make[6]: Entering directory '/home/carns/working/src/darshan/darshan/build-wk/darshan-runtime/lib'
make[6]: *** No rule to make target '../../../darshan-runtime/../modules/autoperf/apxc/darshan-apxc-log-format.h', needed by 'distdir-am'.  Stop.
make[6]: Leaving directory '/home/carns/working/src/darshan/darshan/build-wk/darshan-runtime/lib'
```

**Comment by shanedsnyder** [comment]
I did make some modifications there compared to what was in your PR, @wkliao. The main change was that the darshan-base-ld-opts file no longer needs to be configure generated -- I adopted an approach that you used in other places for the ld-opts to just have them constructed by make rules instead. So there is no longer a `darshan-base-ld-opts.in` file. Maybe the makefile logic isn't quite right on `main`, currently though? I want to generate a file called `darshan-ld-opts` using `darshan-base-ld-opts` and any module-specific ld-opts files based on which modules are enabled at build time:

```
darshan-ld-opts: darshan-base-ld-opts
    cat $< > $@
if BUILD_POSIX_MODULE
    echo '@$(datadir)/ld-opts/darshan-posix-ld-opts' >> $@
endif
...
```

I can reproduce the error @wkliao hits using his make command. I'm not exactly sure what the command is trying to do, but I see that error when it's apparently building darhsan-3.3.0...that version would not be compatible with recent automake changes, right? Maybe the error is expected, unless I'm confused.

**Comment by wkliao** [comment]
Hi @carns 
Please share the command line you are using.

Hi @shanedsnyder 
Command `make distcheck` is to check if the distribution
(created by command `make dist`) works correctly. 
If file `darshan-base-ld-opts` no longer needs to be created
at configure time, then the fix is simply add the file name
into EXTRA_DIST in Makefile.am.

**Comment by carns** [comment]
Whoops, please ignore my error.  I was working on a clone that did not have the submodules set up properly.

Agreed with the discussion that we should just add darshan-base-ld-opts to the dist directly if we don't need to modify it at configure time any more.

**Comment by shanedsnyder** [comment]
Should be fixed now, thanks for the report @wkliao !
