### ISSUE TITLE
generate a simple darshan job summary template with header + footer + log details

### ISSUE THREAD

**Issue by shanedsnyder** [darshan-hpc/darshan#462]
After deciding on the templating engine in #461, we should come up with a simple HTML template for darshan job summaries that only includes some high-level job details. This can serve as a template starting point that we can then build off of when implementing other sections of the report we have targeted for V1 of these tools.

The Python code for generating job summaries will need to extract job metadata from the log to pull out some simple parameters that will be used to quickly provide context about the report in question.

Header is probably something really simple like "app-name (date)", like `ior (11/11/21)`, with some horizontal lines to separate it from following sections of the report.

Footer maybe just something indicating what version of PyDarshan generated the report (e.g., `Job summary generated using PyDarshan 3.3.0.2.`), mostly for us to quickly inspect reports from users to know which versions they are using and things like that. 

The first section of the report should summarize important metadata about the log so users can quickly orient themselves and understand what job the report is for and what the log contains:

![image](https://user-images.githubusercontent.com/24571836/131558479-5c49e1b0-e3b2-4a49-8755-ba49ef9f2608.png)

One new thing we haven't done before is the details about the different modules present in the log at the bottom of the details listed above. We think it will be helpful for users to understand straight away what type of module data is contained in the log, how much data each module produced, and whether any modules ran out of memory at runtime (the warning sign).

**Comment by kevin-harms** [comment]
To add some details, a possible concept is to have:
(*) main template that includes the header, footer and the summary section, and section to hold module specific sections.
(*) sub-template for a module
  (*) includes general module data and info
  (*) allows adding table and plot templates into it
(*) sub-template that has what is needed for enclosing a plot
  (**) a python function that takes a function to produce a plot and then takes the data and encodes it into the plot template and adds it to the module template
(*) sub-template for a table
  (**) a python functions takes a dictionary and applies the data to the table

Hopefully in the main job-summary code we can have a flow like:
  load_template('main')
  update_main_template(job) -> provides all the variables to fill out the header, footer and summary
  for each module:
    m = add_module(foo, main)
    switch (m)
      case POSIX:
          apply_posix_data(m)
      case APMPI:
         apply_apmpi_data(m)
     ...

the module specific functions can then functions to add plots and tables for a given module.

**Comment by tylerjereddy** [comment]
@carns What do you think about closing this issue and opening 1 or two more specific issues re: things that are still missing from the description here, now that I've merged the basic request here in gh-485?

Perhaps an issue for the "warning stuff" Shane mentions? I don't think that is in yet.

**Comment by carns** [comment]
Yeah that sounds good @tylerjereddy .  I think we have converged on a summary template to build on, which was the point of this issue.

**Comment by tylerjereddy** [comment]
Ok, closed, and I opened an issue about warnings--as always, if folks see other issues that should be opened from other content here, please open those.
