### ISSUE TITLE
BLD: pydarshan adjustment needed for rebase

### ISSUE THREAD

**Issue by tylerjereddy** [darshan-hpc/darshan#475]
@shanedsnyder @jakobluettgau @carns 

I don't think CI is running on `main` yet, so this may have slipped through, plus it is a MacOS issue so would need MacOS CI (which I will work on shortly..). 

 When running the test suite on `pydarshan-devel` rebased on latest `main` I see:

`darshan.discover_darshan.DarshanVersionError: This version of PyDarshan requires libdarshan-util 3.3.1, but found 3.3.0`

Looking a little more closely, it seems that on mac we are now generating `libdarshan-util.dylib -> libdarshan-util.0.dylib`
instead of `libdarshan-util.so`, which means `pydarshan` can no longer pick up the build shared object on MacOS with the new build system.

This patch fixes the issue for me locally (has a few comments):

```diff
--- a/darshan-util/pydarshan/darshan/discover_darshan.py
+++ b/darshan-util/pydarshan/darshan/discover_darshan.py
@@ -168,6 +168,15 @@ def find_utils(ffi, libdutil):
         except:
             libdutil = None
 
+    # TODO: constrain this check to MacOS
+    # TODO: don't catch generic Exception, be more
+    # specific
+    if libdutil is None:
+        try:
+            libdutil = ffi.dlopen("libdarshan-util.dylib")
+        except:
+            libdutil = None
+
     if libdutil is None:
         try:
             library_path = discover_darshan_shutil()
```

**Comment by shanedsnyder** [comment]
This makes sense to me, as long as @jakobluettgau doesn't have objections. As you can tell we haven't really had much in terms of testing Mac environments, so that CI will be really useful.

**Comment by jakobluettgau** [comment]
Looks good to me as well.  We could also use something like platform.system() to adjust which names to look out for, but I think just adding another routine sounds fair.

And yeah this definitely shouldn't catch all exceptions, I think there was two relevant ones we would want pass gracefully. I can have a look.

**Comment by tylerjereddy** [comment]
Ok, I merged the small patch so I can proceed with the rebasing process
