### ISSUE TITLE
track per-process information in addition to per-file information

### ISSUE THREAD

**Issue by shanedsnyder** [darshan-hpc/darshan#48]
In GitLab by @shanedsnyder on Sep 24, 2015, 16:25

This ticket would be best done after modularizing the log format (see #46).  In addition to storing per-file records, we could store summary record per process (but spanning files) as well.

For example, we might want to know the total amount of time a process spent doing metadata, reads, and writes, as well as the number of bytes it read and wrote, regardless of how many files it opened or how many threads it used. 

We could use this per-process data (in conjunction with a reduction step) to produce an immediate performance estimate without much post processing.

This also depends on accurate thread accounting in #81.

**Comment by carns** [comment]
This ticket can be closed by #548, it gets the spirit of what we wanted here.
