### ISSUE TITLE
MAINT: Change darshan summary report figure functions to use DarshanReport as input

### ISSUE THREAD

**Issue by nawtrey** [darshan-hpc/darshan#487]
At the moment there is a split in inputs for the functions that generate our report figures: some use the `DarshanReport` object and some use the log path. More specifically, several of the functions in `darshan.experimental.plots` along with the metadata and module table functions in GH-485 use the report object, while `plot_dxt_heatmap.plot_heatmap` and `data_access_by_category.plot_with_log_file` (in GH-397) take the log path as input. 
 
When it comes to building a report from these functions, it seems logical to have them take the `DarshanReport` as input so we don't have to generate new report objects and read in the record data every time we generate a figure. I think it would also make building a "figure registration" system easier down the line. 

We will likely have to add a check to ensure the correct data structures are provided to the figure functions since some of them anticipate `pandas` dataframes.

**Comment by kevin-harms** [comment]
Ideally, the report object can be the input. There might be some cases where you would want to reuse the plot function after filtering/reducing/etc the data. In those cases, taking a pandas data frame directly would be beneficial, but maybe starting with just the report object is easiest.

**Comment by shanedsnyder** [comment]
Yeah, I'd say let's try to use the report object as the input for these plotting functions for uniformity. It's also possible users may want to filter records associated with a report object (i.e., throw out the MPI-IO module info, for whatever reason), so makes sense to take an already constructed report object rather than re-creating a generic one from scratch given a log path.

**Comment by nawtrey** [comment]
With gh-397 merged this can be closed.
