### ISSUE TITLE
TST: ensure summary report assets are distributed properly when installing from a wheel

### ISSUE THREAD

**Issue by nawtrey** [darshan-hpc/darshan#489]
As Tyler discussed [here](https://github.com/darshan-hpc/darshan/pull/485#issuecomment-920504931), there are certain assets (i.e. `.html` and `.css` files) that may not be available when installing Darshan from a wheel. Similar issues have been brought up before, like [here](https://github.com/darshan-hpc/darshan/pull/386#discussion_r650141987) in Kevin's PR, where an adjustment to `MANIFEST.in` was necessary to keep the template code.

Tyler suggested the following:
- have a new CI matrix entry that tests "command line job summary generation from a wheel install"
- it may be most suitable to ensure this can be done inside a conventional regression test without having to use a subprocess--for example, that it is possible to call main() with appropriate arguments on each of the log files in the logs repo and make sure an .html artifact gets generated as expected in a temporary test directory (instead of the command line call proper)

**Comment by tylerjereddy** [comment]
> I don't think we need a CI entry to address this issue since the CI is currently installing pydarshan using a wheel.

Yes, I fixed it myself in gh-506...

**Comment by tylerjereddy** [comment]
Actually, I'm not convinced the testing is sufficient yet for the wheel *install*, I'll comment in one of the other PRs initially
