### ISSUE TITLE
ENH: add warning for modules that ran out of memory

### ISSUE THREAD

**Issue by tylerjereddy** [darshan-hpc/darshan#498]
This (bolded) point was not addressed from gh-462 re: warnings in the html report:

> One new thing we haven't done before is the details about the different modules present in the log at the bottom of the details listed above. We think it will be helpful for users to understand straight away what type of module data is contained in the log, how much data each module produced, **and whether any modules ran out of memory at runtime (the warning sign)**.

![image](https://user-images.githubusercontent.com/7903078/134592516-c0b22cbe-b3fd-4439-84ee-b98ee748c144.png)

**Comment by shanedsnyder** [comment]
I'll make some time this week to add support for this in the bindings so this work can be tackled in the job summary report code.

**Comment by nawtrey** [comment]
The partial flags were implemented in gh-518. Is there anything left to do for this issue? Looking through that PR again, it looks like there was some agreement on adding a parametrized test that check this for all of the logs. But I could close this and open a separate issue for that.

**Comment by nawtrey** [comment]
In our meeting today we concluded we definitely want some sort of flag with an obvious error message like shown above. 

It was also suggested that we try having a general "warning box" at the top of the report that can be filled with various warnings when available, or creating a generic error box that can be reused when necessary. If we only have 1 use case for this it might be okay to just make it work here and then generalize it later though.
