### ISSUE TITLE
BLD: use pyproject.toml

### ISSUE THREAD

**Issue by tylerjereddy** [darshan-hpc/darshan#507]
We should consider using `pyproject.toml` for our wheel builds/install system to comply with [PEP518](https://www.python.org/dev/peps/pep-0518/), and to get in line with modern Python packages here.

**Comment by tylerjereddy** [comment]
I'll see if I can draft this today

**Comment by jakobluettgau** [comment]
Sounds good to me. Until recently we didn't really use many new API additions of numpy, pandas, or matplotlib, but i agree having minimum version prevents headaches in various situations beyond building.

Is there any experience for versions we might want to aim for good site/python compatibility?

**Comment by shanedsnyder** [comment]
I think this is also mostly addressed by #969. `setup.py` is now pretty barebones, with only the `ext_modules` logic and the code for copying in AutoPerf python code (this will probably go away soon if we merge AutoPerf code into the Darshan repo).
