### ISSUE TITLE
ENH: add layout controls to darshan summary report  

### ISSUE THREAD

**Issue by nawtrey** [darshan-hpc/darshan#517]
In the last few meetings we've discussed giving users the option to easily configure their summary report by selecting which plots they want and what sections they want to place them in, but it would be nice to also have the ability to place figures adjacent to each other as well (instead of vertically stacking them). 

The real advantage to this is the `pydarshan` plotting functions would only ever need to generate a single `matplotlib` figure, we wouldn't need to create figures with multiple subfigures because the HTML would be handling the formatting/object placement on its own.

This is lower priority than any of the current pydarshan-job-summary-v1 milestone objectives, but I'm opening an issue now so we can track it moving forward.

**Comment by shanedsnyder** [comment]
I think this is done, as well. We can re-open if we have more specific wants.
