### ISSUE TITLE
ENH: add `LUSTRE` module support to `DarshanRecordCollection.to_df()` 

### ISSUE THREAD

**Issue by nawtrey** [darshan-hpc/darshan#543]
As discussed in gh-533, the `LUSTRE`-specific code path in `to_df()` doesn't provide records containing `pandas.DataFrame`s. 

Adding support for this should be fairly straight forward since the `LUSTRE` records have similar data structures to `POSIX`. To illustrate that point, here is a simple example that would work:
```python
if mod in ['LUSTRE']:
    counters = []
    ost_ids = []
    ids = []
    ranks = []
    for rec in records:
        counters.append(rec['counters'])
        ost_ids.append(rec['ost_ids'])
        ids.append(rec['id'])
        ranks.append(rec['rank'])

    records = {
        "counters": pd.DataFrame(counters, columns=self.report.counters[mod]['counters']),
        "ost_ids": pd.DataFrame(ost_ids, columns=["ost_ids"])
    }
```
This can be simplified/combined with the generic record handling code path (and optimized) but this could work for an initial try.

**Comment by nawtrey** [comment]
@jakobluettgau said this structure was acceptable. I'll look at this today.

**Comment by tylerjereddy** [comment]
Fixed by the cross-linked PR
