### ISSUE TITLE
add per-module bandwidth calculations to pydarshan job summary reports

### ISSUE THREAD

**Issue by shanedsnyder** [darshan-hpc/darshan#555]
(From discussion in #549)

We should add some per-module bandwidth calculations to pydarshan job summary so that users can quickly see roughly what I/O bandwidth they are achieving via different APIs. `darshan-parser` has some code to provide a few different bandwidth calculations that we should figure out how to expose to pydarshan. At the very least, an 'I/O bandwidth by average' and 'I/O bandwidth by slowest' would be useful to display.

**Comment by shanedsnyder** [comment]
In our current job summary tool (i.e., not pydarshan-based), we include some high-level performance information near the top of the report that gives info on total bytes moved and obtained bandwidth across a couple of modules:
![image](https://user-images.githubusercontent.com/24571836/141213975-7b20d6ab-6851-465c-bc64-7612f969916e.png)

I was imagining we could include some general performance numbers like this in these per-module sections we're adding to the pydarshan reports.

This is probably a nice task we could use to think about how to best share some of the performance calculations we've done in our C code to pydarshan, which we've talked off/on about so far but have thus far avoided. As far as priorities go, I think it probably makes sense to think more about once we've got the v1 job summary milestone done, though.

**Comment by carns** [comment]
I like the idea of moving this to a per-module thing.

**Comment by nawtrey** [comment]
In today's meeting we agreed that this can be held off for now since we don't have the cumulative data available on the `pydarshan` side of things. So probably a pydarshan-v2 thing.

**Comment by carns** [comment]
Depends on #642.

**Comment by shanedsnyder** [comment]
This was completed via #898.
