### ISSUE TITLE
ENH: on designing log file retrieval machinery

### ISSUE THREAD

**Issue by tylerjereddy** [darshan-hpc/darshan#566]
# Background

Something that I've been trying to encourage is a system for gracefully retrieving log files, wherever they might reside, in a sustainable/maintainable way.

There are a few problems with the current approaches:

- for the test suite in the main repo, there is a tendency to specify relative paths like the following for log files that are stored in the main repo: `examples/example-logs/dxt.darshan`; this unnecessarily ties the test suite to execution from a certain relative path, and requires developers to use a different approach to retrieve log files from the main repo vs. the logs repo
- at the moment, all current and proposed usage of log files in the main repo test suite requires some level of manual intervention; for example, manually marking those tests cases with a skip like in gh-553 (see below); is it really a useful exercise for developers to manually mark every single log repo file with a `skipif` directive and type out the same message about the logs repo missing over and over?

```python
        pytest.param(
            "imbalanced-io.darshan",
            "POSIX",
            plot_access_histogram,
            [18, 2492, 14679, 0, 50486, 186, 0, 0, 0,
            0, 43, 301, 2, 0, 50486, 0, 0, 0, 0, 0],
            marks=pytest.mark.skipif(not pytest.has_log_repo, # type: ignore
                                    reason="missing darshan_logs"),
```
- the current infrastructure depends on `pytest` fixtures, but the need to robustly handle retrieval of log files from different paths and two projects is shared by other infrastructure: the `asv` benchmarks won't be able to leverage a solution in a `pytest` fixture because it doesn't use `pytest` to run its suite; likewise, if you're working locally with small debug script, you probably also won't gain much convenience from the availability of a solution embedded in a `pytest` fixture
- the logs repo is using yet another approach, which currently requires separate maintenance, to retrieve log files from dictionaries defined the main project, but there is more than one dictionary, and a bunch of conditional logic in the setup process for those benchmarks to select the correct code path

# Proposed Solution

I think we want an approach that reduces duplication/maintenance burden and gracefully handles the presence/absence of the logs repo, and that can be used for both the test suite, the `asv` benchmark suite, and even local debugging scripts.

Here is one approach I was hoping to inspire a bit:

- a utility function that resides in `pydarshan`; can be imported by the test suite, the `asv` suite, and any other external scripts that `import darshan`
- the function accepts a single filename string for a log file and has logic that does the following:
  - search through all paths in the installed `darshan` project that can contain log file assets, and return the absolute path to the installed log file that matches (users no longer worry about something being in `examples` or in another folder, they just provide the log file name)
  - if nothing is found in the main repo for the log filename provided, make an attempt to import the darshan logs project
  - if the import of the darshan logs project fails, and it is detected that you are running `pytest`, use an imperative `pytest.skip(reason)` so that skipping logic, and the skipping message, are maintained in a single location and do not require developers to manually specify the skips/message [if you are not running `pytest`, instaed of using an imperative `pytest.skip`, you probably simply want to raise an exception of the appropriate type, like in the `asv` suite or your own external script trying to find a log file by name]
  - if the import of the darshan logs project succeeds, then return the absolute path to the log filename of interest
  - if there is still no match on the log filename, error out

# Some Considerations

- It seems likely that for the foreseeable future, we'll have logs spread between the main repo and the logs repo, so I don't see the problem disappearing immediately
- This doesn't really require any massive changes--all of the old/current approaches can remain in effect and be progressively removed at whatever pace is appropriate
- for the cases of duplicate log files, we can start to reduce the level of disruption because this function will search until it finds a particular log file, in a manner transparent to the developer (if you delete a duplicate log file, it will simply return the absolute path to the original log file)
- since the logic for file retrieval would be located in one place, modernizing the approach to use i.e., features of `importlib.resources` or whatever else comes along may be a fair bit less work

**Comment by nawtrey** [comment]
I'm going to take a look at this today.

**Comment by tylerjereddy** [comment]
Fixed by gh-587, as long as you don't use the function in `pytest` decorators/parameters (as documented there), which is probably an "ok" compromise for now.

There is considerable potential for useful maintenance follow-ups now that `get_log_path()` is available, and future testing should be able to intertwine main repo and logs repo log file assets much more easily.
