### ISSUE TITLE
DXT heat map plotting code updates

### ISSUE THREAD

**Issue by nawtrey** [darshan-hpc/darshan#575]
There were a few changes suggested in gh-570 for the DXT heatmap plotting code that I'll describe here. These will likely be handled in separate PR's since some will likely be difficult enough on their own. 

Suggested changes:
- [ ] Use stored `end_time` to set the x-axis maximum value, to make comparisons across modules easier (and integrate easier with darshan-runtime heatmap eventually). See comments [1](https://github.com/darshan-hpc/darshan/pull/570#pullrequestreview-820567121) and [2](https://github.com/darshan-hpc/darshan/pull/570#issuecomment-983963683).
- [ ]  ~Find a way to scale the heatmap colorbar such that a single order of magnitude has a noticeable change in color.~
- [x] Use `nprocs - 1` to set the y axis maximum 
- [ ] ~Find a way to label the vertical & horizontal bar graphs such that a user can easily get an idea of how much data is in a given rank. Phil suggested adding some text that explains what the largest value is and what rank it corresponds to (i.e. something like "rank 3 read/wrote the most data @ 200 MiB").~
- [x] Make sure it is compliant with the new runtime heatmap data

I'll probably stave off the majority of these changes until the runtime-heatmap data is accessible, as discussed in today's meeting.

**Comment by tylerjereddy** [comment]
Are there issues open for the anomalies in the heatmaps for the snyder log (weird horizontal sums/rank activity patterns?). It looks like those may be indirectly referenced in comment links above, but only described as a visual matter rather than a potential bug somewhere, so you may want to split those off due to potential severity/clarity.

**Comment by nawtrey** [comment]
That's a good point, I'll open a separate issue for those since they appear to be a bug.

**Comment by nawtrey** [comment]
Out of the remaining tasks, I think tasks 1 and 5 (and arguably 4) are Darshan 3.4 material:
- Task 1 should allow for easier comparison with the runtime heatmaps
- Task 5 is likely going to be handled when the runtime heatmaps get added to the report, if not before
- Task 4 probably isn't too bad to check off, but probably isn't a requirement

If we agree on which tasks we want I can move the non-milestone task(s) to separate issues and mark this one as 3.4.

**Comment by carns** [comment]
Agreed.  I would suggest just putting tasks for 1 and 5 into the 3.4 milestone, and capturing the others outside of a milestone for now but just labeled with the pydarshan tag.

**Comment by nawtrey** [comment]
Okay, I've moved tasks 2 and 4 into their own issues (gh-657 and gh-658, respectively), and updated the issue comment. Lastly, I added it to the 3.4 milestone since we want the remaining tasks resolved for 3.4.

**Comment by shanedsnyder** [comment]
Closing, everything here has been addressed (including x-axis rescaling to runtime) or moved to another issue.
