### ISSUE TITLE
MAINT, TST: number of open files

### ISSUE THREAD

**Issue by tylerjereddy** [darshan-hpc/darshan#578]
While working on gh-397, I had to set `ulimit -n 2048` on my mac locally to avoid a testsuite error: `FAILED tests/test_summary.py::test_main_all_logs_repo_files - OSError: [Errno 24] Too many open files`

This is just an issue so we keep an eye on the number of open file handles in the testsuite/codebase. The error was only reproduced on a single core incantation via `pytest --import-mode=importlib`, so probably started hitting the per-process limit (by default, it was `256` on that machine).

**Comment by jakobluettgau** [comment]
I remember adding the __del__(), __enter__(), __exit__() hooks to make sure opend logs are closed again for a crawler at some point, but apperently it's not int the branch. I'll open a pull request that includes it again.

**Comment by jakobluettgau** [comment]
See https://github.com/darshan-hpc/darshan/pull/583

**Comment by tylerjereddy** [comment]
Should be fixed by cross-listed PR merge.
