### ISSUE TITLE
BUG: Negative `POSIX_MMAPS` counter values 

### ISSUE THREAD

**Issue by nawtrey** [darshan-hpc/darshan#579]
While working on the “Operation Count” plotting code (`plot_opcounts.py`), I noticed the `POSIX_MMAPS` counter was set to zero with [a comment](https://github.com/darshan-hpc/darshan/blob/pydarshan-devel/darshan-util/pydarshan/darshan/experimental/plots/plot_opcounts.py#L51) inquiring about it being faulty. It looks like `POSIX_MMAPS` along with several others (`_FILENOS`, `_DUPS`, `_RENAME_SOURCES`, `_RENAME_TARGETS`) are commonly negative in the testing logs.

For example, here are a few files for which the sum over all records for all 4 counters are negative:

FILE: `sample-badost.darshan`
```
POSIX_FILENOS  -->  -2048
POSIX_DUPS  -->  -2048
POSIX_RENAME_SOURCES  -->  -2048
POSIX_RENAME_TARGETS  -->  -2048
```
FILE: `sample-goodost.darshan`
```
POSIX_FILENOS  -->  -48
POSIX_DUPS  -->  -48
POSIX_RENAME_SOURCES  -->  -48
POSIX_RENAME_TARGETS  -->  -48
```
FILE: `snyder_acme.exe_id1253318_9-27-24239-1515303144625770178_2.darshan`
```
POSIX_FILENOS  -->  -368459
POSIX_DUPS  -->  -368459
POSIX_RENAME_SOURCES  -->  -368459
POSIX_RENAME_TARGETS  -->  -368459
```

This seems like a bug since the counters in question should all be positive values. I should note that the above cases have a -1 for every POSIX record, and there are several other logs that have at least a single record with a negative value.

Maybe @shanedsnyder and/or @jakobluettgau can confirm if this is a `pydarshan` bug?

**Comment by tylerjereddy** [comment]
I assume this issue accounts for the docs indicating:

> A value of -1 indicates that Darshan was unable to collect statistics for that particular counter, and the value should be ignored.

And the various previous discussion with the team about using something better than `-1` longer-term like `np.nan`, etc.

**Comment by tylerjereddy** [comment]
We talked about that in several meetings, so I'm guessing you're talking about something else.

**Comment by tylerjereddy** [comment]
Hmm, it certainly sounds to me like you're just describing the documented behavior for missing values though, looking at the `snyder` log you seem to have just summed up all the missing (`-1) values, so no surprise there?

**Comment by nawtrey** [comment]
> Hmm, it certainly sounds to me like you're just describing the documented behavior for missing values though, looking at the `snyder` log you seem to have just summed up all the missing (`-1`) values, so no surprise there?

Yeah, that seems to be the case then. I guess I was led to believe this was different because of the comment that was left in the plotting code, it seemed like there was an unresolved issue. I'll close this.
