### ISSUE TITLE
Statically building with darshan fails at linker phase

### ISSUE THREAD

**Issue by bebosudo** [darshan-hpc/darshan#585]
Hi,
I built darshan on Perlmutter at NERSC and it works fine for dynamically linked applications
```
$ module load darshan/3.3.1
$ cat hello.c
int main() {}
$ cc hello.c; echo $?
0
$ ldd a.out |grep darshan
	libdarshan.so => /global/common/software/nersc/pm-2021q4/sw/darshan/3.3.1/lib/libdarshan.so
```

But upon trying to build a dummy executable statically with darshan enabled, the link cannot find the fmpich, mpichcxx and lz libraries:
```
$ module load cray-pmi{,-lib}  # only required for static builds
$ cc -static hello.c
/usr/bin/ld: cannot find -lfmpich
/usr/bin/ld: cannot find -lmpichcxx
/usr/bin/ld: cannot find -lz
/usr/bin/ld: cannot find -lz
collect2: error: ld returned 1 exit status
```

Unloading darshan makes it compile fine.
Any idea what it could be? We don't officially support static builds, but it would be a nice thing to support

**Comment by carns** [comment]
Thanks for the bug report @bebosudo .  I just activated my perlmutter account and confirmed the same thing.  It also happens if you enable static compilation with `export CRAYPE_LINK_TYPE=static`, which is something I was curious about.  I'll have a look and see if I can spot the problem.  It seems like either some library paths have been truncated or else they are in the wrong order for the Darshan library.

**Comment by carns** [comment]
I don't have a solution yet, but a few interesting pieces of information:

1) I didn't look closely enough to see if the errors match.  For me, with the default perlmutter environment, I also get this when trying to statically compile, regardless of whether Darshan is loaded or not:
```
/usr/bin/ld: cannot find -lpmi
/usr/bin/ld: cannot find -lpmi2
```

2) The fmpich and mpichcxx errors are sensible enough from the linker's perspective, those libraries don't exist (though there is a dynamic version of the former):
```
$ ls /opt/cray/pe/mpich/8.1.11/ofi/nvidia/20.7/lib
libfmpich.so	     libmpifort_nvidia.so	  libmpi.so
libmpi.a	     libmpifort_nvidia.so.12	  libmpl.so
libmpich.a	     libmpifort_nvidia.so.12.0.0  libopa.so
libmpichf90.a	     libmpifort.so		  libtvmpich.a
libmpichf90.so	     libmpi_nvidia.a		  libtvmpich.so
libmpich.so	     libmpi_nvidia.so		  libtvmpich.so.12
libmpifort.a	     libmpi_nvidia.so.12	  libtvmpich.so.12.0.0
libmpifort_nvidia.a  libmpi_nvidia.so.12.0.0	  pkgconfig
```
We likely need to update our detection of what libraries to include when dynamic linking.  The addition of libfmpich and libmpichcxx a long time ago was helpful in instrumenting Fortran and C++ codes with PMPI, but Darshan no longer uses PMPI.  It's possible they aren't relevant any more, but we'll need to do some testing with some Fortran and C++ codes statically linked to confirm.

3) We need to find a static zlib library to solve that one.  I can't figure out where it is, but it appears that SUSE may have split it out into it's own `zlib-devel-static` package?  https://opensuse.pkgs.org/15.2/opensuse-update-oss-x86_64/zlib-devel-static-1.2.11-lp152.8.3.1.x86_64.rpm.html  Is that something that can be installed on the perlmutter login nodes?

I'll look into 2) .

**Comment by carns** [comment]
@bebosudo the linked PR should fix the MPI library errors.  After we review it a bit it can probably be cherry-picked into a 3.3.1.1 release or similar to pick up the change (origin/main has several other changes that might not be ready for a tagged release yet).

I don't think the -lz or -lpmi linker problems are within Darshan's purview exactly, but we'll need to sort those out as well to be able to fully test static linking with Darshan on perlmutter, I think.

**Comment by bebosudo** [comment]
Hi! I finally had some time to try it out and I confirm that #589 solves the problem above: I tried it both on a simple file with `int main() {}` and while building IOR with `CFLAGS="-static" CC=cc ./configure`, and both work fine.
Thanks Phil!
