### ISSUE TITLE
BUG: `time_plot_heatmap_builtin_logs` benchmark failure

### ISSUE THREAD

**Issue by nawtrey** [darshan-hpc/darshan#586]
Benchmark `asv run -b "time_plot_heatmap_builtin_logs"` returns the following output:

```
================================================ ======== ======== ========
--                                                         xbins           
------------------------------------------------ --------------------------
                darshan_logfile                     10      100      1000  
================================================ ======== ======== ========
 examples/example-logs/ior_hdf5_example.darshan   failed   failed   failed 
       examples/example-logs/dxt.darshan          failed   failed   failed 
     tests/input/sample-dxt-simple.darshan        failed   failed   failed 
================================================ ======== ======== ========
```

I think this is related to the call signature change made to `plot_dxt_heatmap.plot_heatmap()` in gh-535, because running the above benchmark with `-v` flag reveals the following error:

```
File "/Users/nawtrey/darshan_install/darshan/darshan-util/pydarshan/benchmarks/benchmarks/dxt_heatmap.py", line 38, in time_plot_heatmap_builtin_logs
plot_dxt_heatmap.plot_heatmap(

TypeError: plot_heatmap() got an unexpected keyword argument 'log_path'.
``` 

I think the solution is just to update the call signature for `plot_heatmap()` in `time_plot_heatmap_builtin_logs`.

**Comment by tylerjereddy** [comment]
I believe there's also a way to do a sort of lightweight dry-run of all the benchmarks in CI, that is a little more sensitive to these issues than the current crude check we have with `asv check`.

SciPy does this: https://github.com/scipy/scipy/blob/master/.circleci/config.yml#L123

Looks like `asv dev` actually does a lightweight/quick benchmark run that is more likely to catch these kinds of errors.
https://asv.readthedocs.io/en/stable/commands.html#asv-dev

Maybe a little painful to set that up though. I can always try to do it separately and rebase on your fix.

**Comment by tylerjereddy** [comment]
Ok, I don't think there's much we can sensibly do to catch this in CI because we also depend on `asv` to gracefully handle cases where there are failures in a subset of benchmark cases that we expect/don't care about (the returned exit code is still `0`).

We could use i.e., `grep` to search for "problem cases," but that would get ugly pretty fast. So, probably better to apply the simple fix and just carefully check code with i.e., `git grep` when changing call signatures for functions, etc.

**Comment by tylerjereddy** [comment]
Fixed by the cross-listed PR.
