### ISSUE TITLE
Disable darshan when application links against ADIOS dummy MPI implementation

### ISSUE THREAD

**Issue by shanedsnyder** [darshan-hpc/darshan#59]
In GitLab by @shanedsnyder on Sep 24, 2015, 16:25

Using Darshan will cause link time errors in this case because there are no PMPI symbols in the dummy implementation (see alcf-support #158921).  

Ideally Darshan would detect this situation automatically and disable itself, similar to what it does in the case where it detects the presence of another tool using PMPI.

**Comment by shanedsnyder** [comment]
In GitLab by @shanedsnyder on Sep 24, 2015, 16:25

There was a solution for this issue in the last release that relied on looking for weak symbols, but those tests have caused problems in other scenarios.

Need to find another solution or consider removing this functionality and recommending that Darshan be disabled manually when using the ADIOS dummy MPI library.

**Comment by carns** [comment]
This issue is deprecated; ADIOS implementation has changed completely since original issue was opened.
