### ISSUE TITLE
BLD: spack package adjustments for pydarshan

### ISSUE THREAD

**Issue by tylerjereddy** [darshan-hpc/darshan#597]
@tylerjereddy should expand the current utils spackage (see: `spack info darshan-util`) to have `pydarshan` variants for the Python component of the package. Probably to be done locally on a branch of `spack`, and later deployed in our own custom "spack repo" before getting upstreamed.

**Comment by tylerjereddy** [comment]
@carns using branch in https://github.com/tylerjereddy/spack/pull/2, I currently encounter some issues, detailed there, when I try to add on the Python part of the spackage. One of the dangers is that we end up needing custom logic to get the Python install/test working I think (?), all of which is normally handled by the `spack` `PythonPackage` class, while `darshan-util` is fundamentally a `AutotoolsPackage` class/process.

Current incantation is i.e., `spack install darshan-util@pydarshan-devel+apmpi+apxc+pydarshan % gcc@7.4.0`

I suspect we may be better off, short term, with a separate spackage with `spack` `PythonPackage` class usage for `pydarshan`, even if we don't use that solution long-term, so we can avoid our own hacks of `PYTHONPATH` or whatever. If we do that, then it might be something like:

`spack install py-pydarshan@pydarshan-devel+apmpi+apxc % gcc@7.4.0`

**Comment by tylerjereddy** [comment]
That said, the only way to know is probably to try both ways, and see which one is worse. Maybe I'll get to that later today.

**Comment by carns** [comment]
Ah, I see.  I'm in favor of whatever seems most expedient for now.

Possibly in the longer run we could consider a package refactoring, so that darshan-util essentially becomes a meta package that pulls in pydarshan and darshan-c-utils (that's probably not the right name, but you see what I mean) so that you can still get everything by installing the same darshan-util package name as ever, but it's really pulling sub-packages with appropriate build systems for each piece.

**Comment by tylerjereddy** [comment]
@carns using https://github.com/tylerjereddy/spack/pull/3 I can get a basic install to work on a Linux box:

`spack install py-darshan % gcc@7.4.0`

Details on what does/doesn't work is over in that PR/branch. It might be worth testing on one of your machines to see if you reproduce my problem (that kind of `gfortran` symbol error can be flaky, so you may just luck out and succeed on one of your machines). That won't be fun to fix.. SciPy is also moving to `meson` as a new build system, so the team probably wouldn't prioritize a fix, though I could dig deeper.

Feel free to fix some of my deletions/hacks to `darshan-util` spackage--for example, I deleted the post-install sniff testing and was somewhat surprised I had to add a new varient for shared lib builds?

**Comment by tylerjereddy** [comment]
I've also commented upstream in case my colleagues have specific suggestions in this case: https://github.com/scipy/scipy/issues/8325#issuecomment-1007815015

**Comment by tylerjereddy** [comment]
On another LANL cluster, with gcc `9.4.0` instead, I get this when trying to generate a summary report from the `spack` buildout/load of `py-darshan`:

`ImportError: /vast/home/treddy/github_projects/spack/opt/spack/linux-centos8-skylake_avx512/gcc-9.4.0/py-scipy-1.7.3-rmoo5sv7v4hoytqy3kiikqijzqnhy4ms/lib/python3.9/site-packages/scipy/linalg/_interpolative.cpython-39-x86_64-linux-gnu.so: undefined symbol: _ZGVeN8v_cos`

**Comment by tylerjereddy** [comment]
Looks like @carns is reproducing this error now in their `spack` buildout as well.

**Comment by tylerjereddy** [comment]
Reported upstream again here: https://github.com/scipy/scipy/issues/15414

**Comment by tylerjereddy** [comment]
This patch may be worth a try for us: https://github.com/scipy/scipy/issues/15414#issuecomment-1013843880

**Comment by tylerjereddy** [comment]
I'm now able to generate summary reports with `spack`-install `py-darshan` using https://github.com/tylerjereddy/spack/pull/3 with the `compilers.yaml` at: https://github.com/scipy/scipy/issues/15414#issuecomment-1014857525

Scoping down the linking fix would be useful of course, but that's a good start..

**Comment by tylerjereddy** [comment]
NumPy `1.22.2` was released two hours ago--that should fix the Fortran extension issues when building SciPy from source using `spack`, which is one less blocker to a smooth experience here.
