### ISSUE TITLE
ENH: human readable values in "data access by filesystem" figure

### ISSUE THREAD

**Issue by nawtrey** [darshan-hpc/darshan#607]
When gh-397 is merged, @carns suggested the values in the "data access by filesystem" be given in KiB/MiB etc. based on the value, so they are more easily interpreted. He suggested this be done on a case-by-case basis since the bar graphs should make obvious the relative ratios.  

A quick search yielded a StackOverflow [thread](https://stackoverflow.com/questions/1094841/get-human-readable-version-of-file-size) with some potential solutions. One of the responses recommends a package, `humanize`, that has a function for this (`humanize.naturalsize()`), but if we want to avoid another dependency it should be easy enough to write a function for this. 

Whatever solution we go with we will probably use it elsewhere such as the module table, where it is currently hardcoded to KiB.

**Comment by shanedsnyder** [comment]
Closing this as it's currently being tracked in #910.
