### ISSUE TITLE
public logutils API for accumulated / derived metrics

### ISSUE THREAD

**Issue by carns** [darshan-hpc/darshan#642]
The current `darshan-parser` implementation has command line arguments that can be used to produced derived calculations from the records in a Darshan log.  In particular:
- `--total`: displays data as a single summation record for each module.  Many fields are simple summations, others are min, max, or some other metric-specific reduction.
- `--perf`: displays aggregate performance estimates (MiB/s) and related metrics
- `--file`: displays how many files were accessed divided into various categories (read-only etc.)
The `--file-list` and `--file-list-detailed` options can produce summaries at a per-file level as well, but are less frequently used.

The `darshan-job-summary` tool also displays similar information (in the former case relying on `darshan-parser --perf` output):
![darshan-summary-perf](https://user-images.githubusercontent.com/5541937/152372057-405559e3-ff0c-4f55-b648-c82928f39104.png)
![darshan-summary-files](https://user-images.githubusercontent.com/5541937/152372111-20a667d0-b368-40bd-bf1b-5c05dd8902dc.png)

We need to include a variation on this (probably in per-module sections) of the new pydarshan summary tool, but the problem is that the existing logic to calculate these things is embedded in either `darshan-parser` or `darshan-job-summary` and not exposed as a programmatic interface.  It could be duplicated in Python, but this would not only be redundant but would also risk introducing new bugs because the perf estimate and record summation calculations have some subtle corner cases.

The solution is to add new functions to the logutils API that will allow external code (both `darshan-parser` and pydarshan via cffi) to reuse the same well-tested logic.

Here is a proposed API (to be made available in darshan-logutils.h).  The basic idea is for the caller to instantiate a stateful "accumulator" object for a given module type, inject records into it (in the format used by other logutils functions), emit derived metrics, and then destroy the accumulator.  This will allow the caller to instantiate accumulators for different purposes (e.g. to operate on subsets of files rather than all files) and inject records into them as part of the existing record iterator loop.
```
/* opaque (forward) reference to an accumulator.  Internally it will likely use dynamic data structures like hash tables but these
 * do not need to be public
 */
typedef struct darshan_accumulator_st* darshan_accumulator;

/* instantiate a stateful accumulator for a given module.  It will subsequently produce errors if you attempt to inject records
 * from a different module.
 */
int darshan_accumulator_create(enum darshan_module_id id, darshan_accumulator* new_accumulator);

/* add a record to the accumulator.  The record is an untyped void* (size implied by record type) following the convention of
 * other logutils functions.  Multiple records may be injected at once by setting record_count > 1 and packing records into a
 * contiguous memory region.  Or would it be better to make this an explicit array (void** record_array) that isn't necessarily  
 * contiguous?  C users don't really need the array functionality; it is mainly a performance optimization in case Python bindings 
 * can use it to limit Python-C transitions.
 */
int darshan_accumulator_inject(darshan_accumulator accumulator, void* record_array, int record_count);

/* aggregate metrics that can be derived from an accumulator.  If a given record time doesn't support a particular field, then it will
 * be set to -1 (for int64_t values) or NAN (for double values).
 */
struct darshan_derived_metrics {
   int64_t bytes_written_total;
   int64_t bytes_read_total;
   double io_time_slowest_rank;
   double estimated_aggregate_bw;
   int64_t files_accessed_total;
   int64_t files_accessed_read_only;
   /* ... more tbd, these are just possible examples */
};

/* emit derived metrics _and_ a summation record (there is little incremental cost in the C code to doing both in the same pass)
 * The summation_record is in the same format as used by the other logutils function */
int darshan_accumulator_emit(
   darshan_accumulator accumulator,
   struct darshan_derived_metrics* metrics, 
   void** summation_record);

/* frees resources (especially any dynamic internal data structures) associated with an accumulator */
int darshan_accumulator_destroy(darshan_accumulator accumulator);
```
A few notes:
- there will be corresponding module-level function pointers for these functions, so that each module can provide their own implementation
- hopefully we can leverage a lot of the existing logic in `darshan-parser` (see `posix_accum_perf()` and `posix_accum_file()` for examples), just moved and refactored
- as part of this effort, we should take the opportunity to discard derived metric calculations that are no longer used, especially the 3 deprecated performance estimation methods, assuming all 3.x era Darshan logs support the preferred method.
- the `darshan-parser` code should shrink considerably.  Most of the code will reside in module-specific logutil implementations
- some modules will not implement accumulators and will provide NULL function pointers for them.  We need to handle that gracefully

@jakobluettgau and @kevin-harms is there any reason the above code block would cause problems for CFFI?  The only somewhat non-standard thing I see is the forward reference for accumulator instances, but it could be cast to a void* if needed.

Also for @tylerjereddy and @nawtrey, is there a preference for how to express batches of records here in the pydarshan summary use case?

**Comment by nawtrey** [comment]
@carns I'll have to think about your question more, but this appears to be related to issue #555

**Comment by carns** [comment]
> @carns I'll have to think about your question more, but this appears to be related to issue #555

Yes, that's right @nawtrey , thanks for linking them.
