### ISSUE TITLE
add unit testing framework for darshan-util

### ISSUE THREAD

**Issue by carns** [darshan-hpc/darshan#644]
The `darshan-util` portion of the code base needs to adopt a unit testing framework to exercise the native library interface.  This will be helpful in particular before embarking on changes like those described in #642 .  Unlike the `darshan-runtime` component, the C utility libraries can be pretty easily tested on any local development environment.

We could embed munit to organize the tests as is currently done in some of the Mochi repositories (see https://github.com/mochi-hpc/mochi-margo/tree/main/tests/unit-tests for an example).

Small-scoped unit testing could begin by using log files present in the darshan-tests/examples/ subdirectory.  More extensive tests could rely on more interesting log examples from the external darshan-logs repository.

**Comment by shanedsnyder** [comment]
munit was integrated for these purposes in #677 -- closing this.
