### ISSUE TITLE
-wrap error when using HPCToolkit

### ISSUE THREAD

**Issue by shanedsnyder** [darshan-hpc/darshan#65]
In GitLab by @shanedsnyder on Sep 24, 2015, 16:25

  I think there's an issue where -wrap calls are specified when we should be disabling darshan at link. Need to investigate more.

Do you know if there's a conflict between Darshan and Rice HPCToolkit on BG/P (Intrepid)? I'm getting these hpclink errors:

hpclink mpixlf90 -WF,-qfpp=comment -qfixed=120 -O3 -qhot -g -I/home/beres/software/p3d-1/include/ -o runit common.o main.o inits.o time1.o time2.o non1d1.o non1d2.o outen.o out1dsp.o out78sp.o out78.o \
read78sp.o forcew.o forcez.o -L/soft/apps/LAPACK -L/soft/apps/fftw-3.1.2-float/lib -L/home/beres/software/p3d-1/lib -lp3dfft -llapack_bgp -lfftw3f
/bgsys/drivers/V1R4M2_200_2010-100508P/ppc/comm/default/lib/libfmpich.cnk.a(_wcomm_rankf.o): In function `mpi_comm_rank':
/bghome/bgbuild/V1R4M2_200_2010-100508P/ppc/bgp/comm/lib/dev/mpich2/src/binding/f77/comm_rankf.c:190: undefined reference to `__wrap_MPI_Comm_rank'
/bgsys/drivers/V1R4M2_200_2010-100508P/ppc/comm/default/lib/libfmpich.cnk.a(_wfinalizef.o): In function `mpi_finalize':
/bghome/bgbuild/V1R4M2_200_2010-100508P/ppc/bgp/comm/lib/dev/mpich2/src/binding/f77/finalizef.c:190: undefined reference to `__wrap_MPI_Finalize'
/bgsys/drivers/V1R4M2_200_2010-100508P/ppc/comm/default/lib/libfmpich.cnk.a(_winitf.o): In function `mpi_init':
/bghome/bgbuild/V1R4M2_200_2010-100508P/ppc/bgp/comm/lib/dev/mpich2/src/binding/f77/initf.c:196: undefined reference to `__wrap_MPI_Init'

**Comment by carns** [comment]
Deprecated; BG systems are decommissioned.
