### ISSUE TITLE
CI: `pytest 7.0.0` compliance 

### ISSUE THREAD

**Issue by nawtrey** [darshan-hpc/darshan#650]
With the new release of `pytest 7.0.0`, the [CI](https://github.com/darshan-hpc/darshan/runs/5096367960?check_suite_focus=true) is failing the `mypy check` due to unnecessary `# type: ignore` statements:

```
darshan/tests/test_summary.py:145: error: Unused "type: ignore" comment
darshan/tests/test_report.py:30: error: Unused "type: ignore" comment
Found 2 errors in 2 files (checked 60 source files)
Error: Process completed with exit code 1.
```

The lines mentioned in the error message are both instances of the following:

```python 
@pytest.mark.skipif(not pytest.has_log_repo, # type: ignore
                    reason="missing darshan_logs")
```

Tyler pointed out [here](https://github.com/darshan-hpc/darshan/pull/647#issuecomment-1031735236) that this is related to some changes in the latest `pytest` release, where the `pytest` objects are now available for type checking.

One the `pytest` `7.0.0` [page](https://pypi.org/project/pytest/7.0.0/), it lists 3.6+ as the supported python versions, so we should be good there. 

Solution
---------

We might be able to get away with just removing the `# type: ignore` instances, but I'll open a PR on my fork to see if this passes.

**Comment by nawtrey** [comment]
Alright well removing the `# type: ignore` instances allows the CI to pass in gh-651, so I'll open a PR against the main repo.

**Comment by tylerjereddy** [comment]
you already did

**Comment by tylerjereddy** [comment]
Fixed by gh-651 (try to double check which repo you target) thx
