### ISSUE TITLE
integrated runtime heatmap data into summary heatmap figure

### ISSUE THREAD

**Issue by carns** [darshan-hpc/darshan#652]
When DXT is not present, use the DXT heatmap module data to recreate figure.

- [x] new logs repo example that includes heatmap module data (from an actual run)
- [x] new logs repo example that has both heatmap and dxt data for sanity check
- [x] bindings for heatmap module
- [x] summary code to use heatmap data

**Comment by carns** [comment]
We can knock out the first two checkboxes on this with the same run.  @shanedsnyder is looking into running an E3SM benchmark example on Cori for this purpose.

**Comment by shanedsnyder** [comment]
See https://github.com/darshan-hpc/darshan-logs/pull/22 and https://github.com/darshan-hpc/darshan-logs/pull/23 for example logs for this work. The former is a smaller scale example that could be used as a starting point that is easy to visually inspect, the latter is a pretty large-scale stress test once we're confident with the first.

**Comment by nawtrey** [comment]
With gh-615 merged I checked off the bindings.

**Comment by shanedsnyder** [comment]
Closed via #715
