### ISSUE TITLE
normalize heatmap bin_width and nbins across ranks and heatmap types at run time

### ISSUE THREAD

**Issue by carns** [darshan-hpc/darshan#672]
Right now each heatmap record produced by Darshan could have a different number of bins and/or bin width depending on when I/O occurred for that particular I/O method on a given rank.

I think the analysis APIs could normalize this for plotting purposes, but it looks like it could be done at runtime without much trouble and probably save a lot of confusion.  The number of bins and width will still be variable, but the values can match across all heatmap records.

As far as implementation, I think the solution is to implement the `mod_redux_func()` hook in darshan-heatmap.c and use it to perform a reduction operation and have all ranks agree on the stop time for heatmap measurements.  The existing `mod_output_func()` function already iterates through all records and prunes bins that extend beyond execution end time.  It just needs to be augmented to a) also call `collapse_heatmap()` to extend the bin width to include execution end time and b) use the agreed-upon collective end time if present.

If all heatmaps use the same end time for this calculation then they will all produce identical bin widths and nbins without further coordination.

This will not change the log format; we will still record width and bin count per heatmap record.

@shanedsnyder @jakobluettgau @nawtrey @tylerjereddy tagging you because this might change what needs to be done on the analysis side to parse the heatmaps.  We probably also want to regenerate the example logs so that they produce data as described here.

**Comment by shanedsnyder** [comment]
(Related to issues discussed #615)

Thinking about it more this morning, fixing this in darshan-runtime might just be the easiest -- at the very least, PyDarshan is probably the wrong spot to fix it since it would only apply to PyDarshan based tools.

**Comment by tylerjereddy** [comment]
In short, you're suggesting that the runtime will always return a rectangular data structure? This trades storage space ("density") for convenience I suppose. The Python side will likely need to convert to the "dense" form anyway, if only briefly.

**Comment by carns** [comment]
They data structures were rectangular already; this is just making sure that all of the rectangles have the same granularity and dimensions, essentially.

**Comment by tylerjereddy** [comment]
Hmm, I don't think Python would consider a different number of columns (`nbins`) for some rows in a row x column data structure to be rectangular.

```
nbins ---->

xxxxxxxx
xxxxxxxxxxxxxxxxxxxxxxxxx
xxxxxxxxxx
```

Those 3 records are jagged rather than rectangular from Python (NumPy/pandas) viewpoint.

**Comment by carns** [comment]
Ah, you are talking about combining multiple heatmap records then.  Yeah, this will make something rectangular that was not before.  I don't think it's increasing memory consumption, though.  For the most part nbins are being reduced  rather than extended to make them line up.

**Comment by tylerjereddy** [comment]
I guess I'm thinking of the case where say 1 rank writes the whole time and a bunch of other ranks only write for one or two short burts--in the previous approach I might imagine we could save some space by using less bins for the ranks that are vastly less active (not even store the `0`s).

In the end, Python would basically need to zero-fill/upsample the less active ranks to get rectangular anyway though.

**Comment by carns** [comment]
Gotcha.  Darshan's log format as a whole errs on the side of simplicity and just relies on general compression to collapse 0s for the in-file format, but that doesn't help memory consumption for whoever is reading the log.  Maybe something to think about in the future.
