### ISSUE TITLE
heatmap records are retained for modules that don't save any records

### ISSUE THREAD

**Issue by shanedsnyder** [darshan-hpc/darshan#693]
As an example, see the following darshan-parser output for a log that demonstrates this issue:
```
# log file regions
# -------------------------------------------------------
# header: 360 bytes (uncompressed)
# job data: 514 bytes (compressed)
# record table: 108 bytes (compressed)
# STDIO module: 57 bytes (compressed), ver=2
# HEATMAP module: 81 bytes (compressed), ver=1

<...>

#<module>       <rank>  <record id>     <counter>       <value> <file name>     <mount pt>      <fs type>
HEATMAP 0       16592106915301738621    HEATMAP_F_BIN_WIDTH_SECONDS     0.100000        heatmap:POSIX   UNKNOWN UNKNOWN
HEATMAP 0       16592106915301738621    HEATMAP_READ_BIN_0      0       heatmap:POSIX   UNKNOWN UNKNOWN
HEATMAP 0       16592106915301738621    HEATMAP_WRITE_BIN_0     0       heatmap:POSIX   UNKNOWN UNKNOWN
HEATMAP 0       3668870418325792824     HEATMAP_F_BIN_WIDTH_SECONDS     0.100000        heatmap:MPIIO   UNKNOWN UNKNOWN
HEATMAP 0       3668870418325792824     HEATMAP_READ_BIN_0      0       heatmap:MPIIO   UNKNOWN UNKNOWN
HEATMAP 0       3668870418325792824     HEATMAP_WRITE_BIN_0     0       heatmap:MPIIO   UNKNOWN UNKNOWN
HEATMAP 0       3989511027826779520     HEATMAP_F_BIN_WIDTH_SECONDS     0.100000        heatmap:STDIO   UNKNOWN UNKNOWN
HEATMAP 0       3989511027826779520     HEATMAP_READ_BIN_0      0       heatmap:STDIO   UNKNOWN UNKNOWN
HEATMAP 0       3989511027826779520     HEATMAP_WRITE_BIN_0     321     heatmap:STDIO   UNKNOWN UNKNOWN
```
To avoid wasting space in the log file (especially for longer running apps), we should probably detect when a heatmap is "empty" and just throw out the record at shutdown time.

This problem can reproduced by using `DARSHAN_EXCLUDE_DIRS` to filter out directories where an application writes to -- this will cause Darshan to initialize the instrumentation module in question, but it will have 0 records associated with it and have a zeroed out heatmap data structure.

**Comment by carns** [comment]
@shanedsnyder I accidentally pushed a fix for this directly into origin/main just now at https://github.com/darshan-hpc/darshan/commit/eb2e0205f1755f7b8e4c1ab8b298061d47c7133e.  I meant to do a PR :-(

Can you sanity check that commit?  If it looks ok we can close this issue.

**Comment by shanedsnyder** [comment]
I think main looks good to go now @carns , I'll close this.
