### ISSUE TITLE
ENH: multiple operation aggregation for `Heatmap.to_df()` method

### ISSUE THREAD

**Issue by nawtrey** [darshan-hpc/darshan#697]
The current method for retrieving the runtime IO heatmap with both "read" and "write" data is to run something like the following:

```python
rd_df = report.heatmaps["POSIX"].to_df(op="read")
wr_df = report.heatmaps["POSIX"].to_df(op="write")
rd_wr_df = rd_df + wr_df
```

I think it would be nice if we could input multiple operations and retrieve the summed dataframe directly from the `to_df()` method instead of handling it downstream. So the above dataframe could be generated with just:

```python
rd_wr_df = report.heatmaps["POSIX"].to_df(ops=["read", "write"])
```

This is how it is handled in `plot_heatmap()` and `get_aggregate_data()`, so I think it would be good to keep them consistent.

**Comment by tylerjereddy** [comment]
Fixed by gh-702
