### ISSUE TITLE
BUG: darshan-runtime forked processes are no longer instrumenting properly

### ISSUE THREAD

**Issue by shanedsnyder** [darshan-hpc/darshan#786]
Recent versions of Darshan are no longer able to instrument child processes of `fork()`. This was working in 3.3.1, so was a recent regression.

Child processes are able to generate Darshan logs fine, but they contain no data. Simple reproducer below:

```C
#include <stdio.h>
#include <stdlib.h>
#include <unistd.h>
#include <sys/types.h>
#include <sys/stat.h>
#include <fcntl.h>

int main(int argc, char *argv[])
{
    int fd;

    fd = open("pre-fork", O_CREAT | O_RDWR, 0644);

    if(fork() == 0)
    {
        close(fd);
        fd = open("post-fork-child", O_CREAT | O_RDWR, 0644);
        close(fd);

        return 0;
    }

    close(fd);
    fd = open("post-fork-parent", O_CREAT | O_RDWR, 0644);
    close(fd);

    return 0;
}
```

Parent processes have log records for "pre-fork" and "post-fork-parent", but child processes create no records.

**Comment by tylerjereddy** [comment]
Fixed by gh-827
