### ISSUE TITLE
Pydarshan: Juypter Notebook install , Not able to find whl package for darshan-utils

### ISSUE THREAD

**Issue by karanveersingh5623** [darshan-hpc/darshan#792]
Hi team

I wanted to run pydarshan on Anaconda Juypter notebook running on my windows client machine .
Not able to find whl package for darshan-utils . Please guide

`RuntimeError: Could not find libdarshan-util.so! Is darshan-util installed? Please ensure one of the the following: 1) export LD_LIBRARY_PATH=<path-to-libdarshan-util.so>, or 2) darshan-parser can found using the PATH variable, or 3) pkg-config can resolve pkg-config --path darshan-util, or 4) install a wheel that includes darshan-utils via pip.`

**Comment by shanedsnyder** [comment]
How exactly did you install PyDarshan in your Anaconda environment? Just running `pip install darshan` (i.e., from PyPI)? Or did you install manually from source?

Generally speaking, the wheels for PyDarshan should include the needed `darshan-util` shared libraries and PyDarshan should be able to find them automatically, but maybe that isn't working somehow in the Anaconda environment.

In any case, if your PyDarshan wheels aren't shipping with a shared library, you will probably need to install them manually and point to them using LD_LIBRARY_PATH as the error message indicates. For PyDarshan 3.4.0.1, that would mean you would need to install `darshan-util` from our 3.4.0 release.

**Comment by tylerjereddy** [comment]
> windows client machine 

I'm pretty sure we don't provide pre-built wheels/binaries for Windows, so the build almost certainly has to be from source. Not sure what our status is on Windows support on the util/pydarshan side--if it isn't actually too bad then we may want to add that to CI testing as well, if only for a single job.

**Comment by shanedsnyder** [comment]
Oh, whoops, good call @tylerjereddy -- was confused thinking this was still Centos.

But yeah, I've not tried personally, but I don't think Windows is supported by PyDarshan and/or darshan-util. Might be worth a try to see how much of a problem it ultimately is.

**Comment by jakobluettgau** [comment]
Currently only the manylinux wheels come darshan-util bundled in.

A relatively easy way to use PyDarshan on Windows, may be to give https://docs.microsoft.com/en-us/windows/wsl/install a try. It would mean to setup your python environment again from within WSL though.

**Comment by shanedsnyder** [comment]
Closing this as there have not been any recent updates.
