### ISSUE TITLE
Another memory leak in PyDarshan

### ISSUE THREAD

**Issue by jesse-r-s-hines** [darshan-hpc/darshan#824]
I've come across another memory leak while working with PyDarshan. I'm running the current `main` branch, compiled locally on Ubuntu 20.04, and using Python3.9.14

Running this code will slowly leak memory:
```python
def leak(report_file):
    with darshan.DarshanReport(report_file, read_all=True, lookup_name_records=True) as report:
        pass

for i in range(1_000_000):
    leak("sample.darshan")
```

Running this code without `read_all=True` doesn't leak anymore (as it was fixed in #811):
```python
def no_leak(report_file):
    with darshan.DarshanReport(report_file, read_all=False, lookup_name_records=True) as report:
        for row in report.mod_records('POSIX'):
            pass
```

The issue appears to occur with any darshan file, but here's a [sample](https://github.com/darshan-hpc/darshan/files/9568265/sample.darshan.zip) that is showing the leak.

**Comment by tylerjereddy** [comment]
The leak is somewhat diminished if I turn off `libdutil.darshan_log_get_filtered_name_records()` but I'm still investigating as a simple `darshan_free` on an associated buffer doesn't look sufficient there. There are a bunch of internal `malloc()` ops on the C side in this control flow...

**Comment by shanedsnyder** [comment]
Just merged in some more changes to PyDarshan/Darshan code that should work around these memory leaks reported here. Appears to resolve the leaks on my end.

Thanks again for the report and please let us know if you find more.
