### ISSUE TITLE
Is autoperf-apmpi-ld-opts used?

### ISSUE THREAD

**Issue by wkliao** [darshan-hpc/darshan#846]
I wonder if `autoperf-apmpi-ld-opts` is still used by darshan-runtime.
When I removed all the lines referring to it in `darshan-runtime/share/ld-opts/Makefile.am`,
make check ran just fine.

https://github.com/darshan-hpc/darshan/blob/cb20d4929728bcb6a94533de79ab088b725bf9e1/darshan-runtime/share/ld-opts/Makefile.am#L31-L38

**Comment by shanedsnyder** [comment]
Yes, this file is still used for statically-linked apps that have APMPI instrumentation enabled.

Basically, every Darshan instrumentation module that intercepts application function calls must define one of these ld-opts files that lists all functions to be wrapped. This functionality is only needed for statically-linked executables, in which case Darshan must specify the entire list of functions via compiler options when the application is being compiled.
