### ISSUE TITLE
PyDarshan job summary cleanup

### ISSUE THREAD

**Issue by shanedsnyder** [darshan-hpc/darshan#910]
From an in-person review of the current Darshan job summary reports at Argonne, it would be nice to try to address as much of this as we can before doing a release.

First some high-level things up for discussion:
- [x] drop blue I/O performance estimate text box, and instead add a per-module table detailing key details of the module (including total files/datasets(H5D)/variables(PNETCDF_VAR) accessed, total bytes read/written, and I/O performance estimate)
  - this way, each module starts off with a high-level summary table that describes key details of I/O, and gets rid of awkward text object we are using now
- [x] disable DXT heatmap plot generation by default, print warning if DXT is available but HEATMAP isn't, and add CLI option to force DXT usage
  - for some logs, it's probably just too expensive to generate DXT heatmaps by default, so this protects against that
  - this would require us to either push a little on CLI stuff in #809 or use something simple temporarily?
- [x] after dust settles, potentially reorganize plots/tables in per-module sections?
  - nothing concrete to suggest just yet (Tyler -0.5 on this)

Smaller things:
- [x] Captions are hard to read (light colored text, also italicized)
![image](https://user-images.githubusercontent.com/24571836/221916109-98e51b3f-8476-46b4-9f5c-903809fdd152.png)
- [x] Add "% runtime" y-axis label to right-side of I/O cost plot
![image](https://user-images.githubusercontent.com/24571836/221916672-29cfb0ba-f4ef-4e7d-967a-200cac298ed6.png)
- [x] Offset autolabeling text at 45 degrees in access size histogram plot and POSIX access pattern plot as is done in I/O op count graph
- [x] Don't autolabel 0 values to further help with cluttering of plots
- [x] If not too complicated, can we add more buffer to top of these plots to avoid autolabels overlapping with plot boundaries?
- [x] We should use a ylim of 0 for access histogram and op count plots to ensure no negative values are plotted.
![image](https://user-images.githubusercontent.com/24571836/221917799-2c6a0fe4-390a-4f8d-871c-1edbbd76e7f1.png)
- [x] Erroneous "type" row in File Count Summary table
![image](https://user-images.githubusercontent.com/24571836/221918843-c533dbd9-3097-4930-81e6-f66dd133a96c.png)
- [x] drop scientific notation entirely (partially addressed in #812?), and rely on humanize to generate sensible human readable byte strings?
- [x] File access by category table font really small
![image](https://user-images.githubusercontent.com/24571836/221919847-46f8a5ad-43c2-4b6b-bc8b-9d03fbc4fe1e.png)
- [x] Pointed out in #907, add a forgotten space to our warning string when a log has no data

**Comment by tylerjereddy** [comment]
There is some duplication with i.e., gh-804 here as well.

**Comment by shanedsnyder** [comment]
I embarrassingly can't figure this one out:

`Erroneous "type" row in File Count Summary table`

Seems like it ought to be a one-liner to move the "type" index up to a column like other values, but I can't quite seem to pull it off.

Most of the other issues I've already addressed in #907

**Comment by shanedsnyder** [comment]
Last bits of this closed via #927.
