### ISSUE TITLE
strange behavior with DXT MPI-IO heatmap

### ISSUE THREAD

**Issue by roblatham00** [darshan-hpc/darshan#914]
I am digging into an application that reads five HDF5 files.  When I turned on DXT, the python report showed an unusual graph for the DXT heatmap.   Here's a screen shot of that report:

![image](https://user-images.githubusercontent.com/2278417/223757441-8a85a40d-1bb4-42c1-8f76-90c6207519aa.png)

heatmap behaves as I would expect:  a bunch of HDF5 reads, followed by a long period of computation
and posix HEATMAP vs DXT looks nominal.
just eyeballing, it looks like DXT_MPIIO plotted everything in the HEATMAP case but left out the non-io parts.
See that big white patch in the heat map case? That's where the app is doing computation.  There's no computation in the dxt case.  The plot still knows there's 200-some seconds of runtime, but in the dxt case the io calls are scaled weird...to fill up the whole plot.

I've attached a zip file with the darshan log and the generated html.  

[dxt-mpiio-heatmap-from-hepps.zip](https://github.com/darshan-hpc/darshan/files/10922186/dxt-mpiio-heatmap-from-hepps.zip)

**Comment by tylerjereddy** [comment]
Reproduced on latest `main`, I'll try to look into it
