### ISSUE TITLE
Segfault within bash when excluded

### ISSUE THREAD

**Issue by dev-zero** [darshan-hpc/darshan#919]
I built Darshain without MPI, within a container. When running bash with darshan LD_PRELOADed and excluded, every `system(...)` call seems to segfault:

```
5997e87a8f78:/darshan # LD_PRELOAD=/darshan/lib/libdarshan.so DARSHAN_APP_EXCLUDE=bash DARSHAN_ENABLE_NONMPI=1 /bin/bash
5997e87a8f78:/darshan # foo=bar
5997e87a8f78:/darshan # echo $foo
bar
5997e87a8f78:/darshan # env
Segmentation fault
5997e87a8f78:/darshan # ls
Segmentation fault
5997e87a8f78:/darshan #
```

**Comment by dev-zero** [comment]
The use case is that I want to profile other apps contained within containers and called by bash scripts. Running the containers with `-e LD_PRELOAD=...` after having copied darshan from my builder container is the easiest way to get there.

**Comment by shanedsnyder** [comment]
Thanks for the details. Looks like there could be a Darshan bug here related specifically to processes that are calling `fork()`. It may be that I didn't run anything that was forking so I didn't hit the issue.

Let me investigate more and see if I can get a fix for this.

**Comment by dev-zero** [comment]
It may be a bit more complicated. Running:
```
9943fe2864fe:/darshan # LD_PRELOAD=/darshan/lib/libdarshan.so DARSHAN_APP_EXCLUDE=bash DARSHAN_ENABLE_NONMPI=1 /bin/bash -c 'ls'
bin  include  lib  share
9943fe2864fe:/darshan # LD_PRELOAD=/darshan/lib/libdarshan.so DARSHAN_APP_EXCLUDE=bash DARSHAN_ENABLE_NONMPI=1 /bin/bash
9943fe2864fe:/darshan # ls
Segmentation fault (core dumped)
9943fe2864fe:/darshan # exit
```

So, only when `bash` is running interactively.

**Comment by shanedsnyder** [comment]
Could you perhaps provide more details on how to setup the container you used and how you installed Darshan? I cannot seem to get a reproducer for this on my laptop, using the different `bash` commands you used above, as well as trying to force the behavior using applications I know call `fork()`.

**Comment by dev-zero** [comment]
For a layman like me it looks like a race condition, and when checking `darshan_core_initialize` it looks like there are some codepaths where the fork handler is setup, but the main global object is not initialised, like this one: https://github.com/darshan-hpc/darshan/blob/f95e9a28d52d15dc02d22f9bb6b337dd35995553/darshan-runtime/lib/darshan-core.c#L335-L343
On the other hand should that have been triggered long time ago if that were the case.
Sorry, no other clues from my side.

**Comment by shanedsnyder** [comment]
A couple of updates:

1.  I can reproduce the crash using your Dockerfile and suggested commands. I'll see if I can find any sort of race or other bug that could lead to it.
2. Ignoring that, I can't seem to generate a Darshan log for anything in the container. Have you had any success with that? I haven't had much of a chance to debug why yet, but it kind of looks like Darshan shutdown never gets called (it does get initialized I confirmed). I don't know what would cause that -- Darshan shutdown is initiated as a destructor for when the Darshan shared library is unloaded.

**Comment by shanedsnyder** [comment]
I did find and fix a bug that is waiting in a PR now, if you're interested in trying it out: https://github.com/darshan-hpc/darshan/pull/922

I think this bug was not actually a race, but just that Darshan was not properly handling the case where an app that is excluded (via APP_EXCLUDE) is calling `fork()`. Darshan has handlers that are called on `fork()`, and they expected some internal Darshan library state to be set that is clearly not set in the case where an app is excluded.

Thanks for reporting this! And let me know if you have other issues (like the other issue I mention above about not generating any Darshan logs).

**Comment by dev-zero** [comment]
Sorry for the late reply and thanks for the fix. I just tested it and the crash is gone.
As for the logs: assuming you mean the Darshan "trace" logs for the application, then yes, I was able to generate them for the application within a container and got the complete report out of it.
