### ISSUE TITLE
report I/O time in darshan-parser

### ISSUE THREAD

**Issue by shanedsnyder** [darshan-hpc/darshan#92]
In GitLab by @shanedsnyder on Sep 24, 2015, 16:26

As reported by Huong Luu, UIUC:

currently Darshan parser reports aggregate performance (computed by total_bytes/time). When I parse the output log, I have to compute the I/O time by reverse (total_bytes/agg_perf). When user uses text files, total_bytes = 0 --> I/O time is lost.

So I think it would be nice if the darshan parser can output the I/O time AND the aggregate performance.

**Comment by carns** [comment]
Deprecated by #245
