### ISSUE TITLE
Lack of IO monitoring on an ACLF DLIO benchmark

### ISSUE THREAD

**Issue by tylerjereddy** [darshan-hpc/darshan#948]
We may want to investigate this one: https://github.com/argonne-lcf/dlio_benchmark/blob/main/dlio_benchmark/configs/workload/unet3d.yaml

Report from Sandra Mendez on Slack that darshan runtime may not have been tracing the files that are opened by the `pytorch` data loader.

**Comment by tylerjereddy** [comment]
Probably related to gh-872.

**Comment by shanedsnyder** [comment]
Closing as I think this is resolved by #978
