### ISSUE TITLE
configure with Lustre not working

### ISSUE THREAD

**Issue by wadudmiah** [darshan-hpc/darshan#997]
Hi,

I am trying to configure Darshan to be built with the Lustre module:

```
export CPPFLAGS=-I/home/kunet.ae/ku1324/lustre/usr/include
export LDFLAGS=-L/home/kunet.ae/ku1324/lustre/usr/lib64
./configure --prefix=$HOME/darshan-3.4.5 --with-log-path=/darshan-logs --with-jobid-env=$SLURM_JOB_ID CC=mpicc --enable-lustre-mod
```

This produces the partial output of:

```
[ ... ]
checking lustre/lustreapi.h usability... yes
checking lustre/lustreapi.h presence... yes
checking for lustre/lustreapi.h... yes
checking for llapi_layout_get_by_xattr in -llustreapi... yes
configure: error: Cannot find required headers for the Lustre module
```
As you can see, it has found the presence of the `lustreapi.h` header file and also found the `liblustreapi.a` library, so I do not know why the configure is failing. The symbol `llapi_layout_get_by_xattr` exists in the Lustre API library:
```
$ nm ./liblustreapi.a | grep llapi_layout_get_by_xattr
0000000000000bd0 T llapi_layout_get_by_xattr
```
Attached is the `config.log`. Any help will be greatly appreciated. 

[config.log](https://github.com/user-attachments/files/16176633/config.log)

**Comment by shanedsnyder** [comment]
Thanks for the report!

I actually observed this behavior recently while working on revamping Darshan's Lustre module (#991) and implemented a fix for it. That should be included in our next release (along with a generally improved Lustre module, capturing much of the details provided by Lustre's `lfs` tool), but probably won't be available for another month or 2.

FYI, this bug only occurs when explicitly passing `--enable-lustre-mod` to Darshan's configure script. If you don't pass that option, Darshan will try to autodetect if Lustre is available and enable it if found. I do *not* see this error and am able to use the Lustre module fine if I just do not pass that argument to configure and rely on the autodetect functionality. Hopefully that route works for you, too, but we'll try to have this cleaned up for the next release in any case.

**Comment by wadudmiah** [comment]
Hi @shanedsnyder, I can confirm it now works for me by dropping the `--enable-lustre-mod` flag. I set up the `CPPFLAGS` and `LDFLAGS` variables it was able to detect the Lustre development header files and libraries. Cheers for the quick resolution.

Regards,
